export default {
	scalars: [
		2, 5, 6, 7, 9, 11, 12, 13, 22, 23, 35, 49, 71, 76, 81, 83, 87, 92, 97, 102,
		106, 123, 129, 137, 157, 163, 169, 175, 181, 187, 193, 199, 205, 211, 217,
		223, 229, 235, 241, 249,
	],
	types: {
		Query: {
			query: [0],
			nodeId: [2],
			node: [
				1,
				{
					nodeId: [2, 'ID!'],
				},
			],
			versionInfos: [
				3,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [13, '[VersionInfosOrderBy!]'],
					condition: [14],
					filter: [15],
				},
			],
			favorites: [
				19,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [23, '[FavoritesOrderBy!]'],
					condition: [24],
					filter: [25],
				},
			],
			levels: [
				152,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [129, '[LevelsOrderBy!]'],
					condition: [130],
					filter: [42],
				},
			],
			levelItems: [
				68,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [71, '[LevelItemsOrderBy!]'],
					condition: [72],
					filter: [45],
				},
			],
			levelMetadata: [
				73,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [76, '[LevelMetadataOrderBy!]'],
					condition: [77],
					filter: [47],
				},
			],
			levelPoints: [
				78,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [81, '[LevelPointsOrderBy!]'],
					condition: [82],
					filter: [51],
				},
			],
			levelRequests: [
				154,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [157, '[LevelRequestsOrderBy!]'],
					condition: [158],
					filter: [159],
				},
			],
			personalBestGlobals: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			records: [
				85,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [87, '[RecordsOrderBy!]'],
					condition: [88],
					filter: [33],
				},
			],
			recordMedias: [
				120,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [123, '[RecordMediaOrderBy!]'],
					condition: [124],
					filter: [38],
				},
			],
			sampledFavorites: [
				160,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [163, '[SampledFavoritesOrderBy!]'],
					condition: [164],
					filter: [165],
				},
			],
			sampledLevels: [
				166,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [169, '[SampledLevelsOrderBy!]'],
					condition: [170],
					filter: [171],
				},
			],
			sampledLevelItems: [
				172,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [175, '[SampledLevelItemsOrderBy!]'],
					condition: [176],
					filter: [177],
				},
			],
			sampledLevelMetadata: [
				178,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [181, '[SampledLevelMetadataOrderBy!]'],
					condition: [182],
					filter: [183],
				},
			],
			sampledLevelPoints: [
				184,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [187, '[SampledLevelPointsOrderBy!]'],
					condition: [188],
					filter: [189],
				},
			],
			sampledLevelRequests: [
				190,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [193, '[SampledLevelRequestsOrderBy!]'],
					condition: [194],
					filter: [195],
				},
			],
			sampledPersonalBestGlobals: [
				196,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [199, '[SampledPersonalBestGlobalsOrderBy!]'],
					condition: [200],
					filter: [201],
				},
			],
			sampledRecords: [
				202,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [205, '[SampledRecordsOrderBy!]'],
					condition: [206],
					filter: [207],
				},
			],
			sampledRecordMedias: [
				208,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [211, '[SampledRecordMediaOrderBy!]'],
					condition: [212],
					filter: [213],
				},
			],
			sampledUpvotes: [
				214,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [217, '[SampledUpvotesOrderBy!]'],
					condition: [218],
					filter: [219],
				},
			],
			sampledUsers: [
				220,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [223, '[SampledUsersOrderBy!]'],
					condition: [224],
					filter: [225],
				},
			],
			sampledUserPoints: [
				226,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [229, '[SampledUserPointsOrderBy!]'],
					condition: [230],
					filter: [231],
				},
			],
			sampledVersions: [
				232,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [235, '[SampledVersionsOrderBy!]'],
					condition: [236],
					filter: [237],
				},
			],
			sampledWorldRecordGlobals: [
				238,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [241, '[SampledWorldRecordGlobalsOrderBy!]'],
					condition: [242],
					filter: [243],
				},
			],
			upvotes: [
				89,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [92, '[UpvotesOrderBy!]'],
					condition: [93],
					filter: [55],
				},
			],
			users: [
				244,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [106, '[UsersOrderBy!]'],
					condition: [107],
					filter: [27],
				},
			],
			userPoints: [
				134,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [137, '[UserPointsOrderBy!]'],
					condition: [138],
					filter: [60],
				},
			],
			versions: [
				246,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [249, '[VersionsOrderBy!]'],
					condition: [250],
					filter: [251],
				},
			],
			votes: [
				99,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [102, '[VotesOrderBy!]'],
					condition: [103],
					filter: [58],
				},
			],
			worldRecordGlobals: [
				94,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [97, '[WorldRecordGlobalsOrderBy!]'],
					condition: [98],
					filter: [41],
				},
			],
			favorite: [
				20,
				{
					id: [12, 'Int!'],
				},
			],
			level: [
				67,
				{
					id: [12, 'Int!'],
				},
			],
			levelByHash: [
				67,
				{
					hash: [7, 'String!'],
				},
			],
			levelItem: [
				69,
				{
					id: [12, 'Int!'],
				},
			],
			levelMetadatum: [
				74,
				{
					id: [12, 'Int!'],
				},
			],
			levelPoint: [
				79,
				{
					id: [12, 'Int!'],
				},
			],
			levelRequest: [
				155,
				{
					id: [12, 'Int!'],
				},
			],
			personalBestGlobal: [
				65,
				{
					id: [12, 'Int!'],
				},
			],
			record: [
				66,
				{
					id: [12, 'Int!'],
				},
			],
			recordMedia: [
				121,
				{
					id: [12, 'Int!'],
				},
			],
			upvote: [
				90,
				{
					id: [12, 'Int!'],
				},
			],
			user: [
				21,
				{
					id: [12, 'Int!'],
				},
			],
			userPoint: [
				135,
				{
					id: [12, 'Int!'],
				},
			],
			version: [
				247,
				{
					id: [12, 'Int!'],
				},
			],
			vote: [
				100,
				{
					id: [12, 'Int!'],
				},
			],
			worldRecordGlobal: [
				95,
				{
					id: [12, 'Int!'],
				},
			],
			zRtm: [
				252,
				{
					pMinAuthorTime: [35],
					pMaxAuthorTime: [35],
					pMinRecords: [12],
					pMaxRecords: [12],
					pExcludedAuthorIds: [12, '[Int]'],
					pExcludedHashes: [7, '[String]'],
					pMinCheckpoints: [12],
					pMaxCheckpoints: [12],
					pMinFinishes: [12],
					pMaxFinishes: [12],
					pMinBlocks: [12],
					pMaxBlocks: [12],
					pSampleSize: [12],
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					filter: [255],
				},
			],
			favoriteByNodeId: [
				20,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelByNodeId: [
				67,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelItemByNodeId: [
				69,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelMetadatumByNodeId: [
				74,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelPointByNodeId: [
				79,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelRequestByNodeId: [
				155,
				{
					nodeId: [2, 'ID!'],
				},
			],
			personalBestGlobalByNodeId: [
				65,
				{
					nodeId: [2, 'ID!'],
				},
			],
			recordByNodeId: [
				66,
				{
					nodeId: [2, 'ID!'],
				},
			],
			recordMediaByNodeId: [
				121,
				{
					nodeId: [2, 'ID!'],
				},
			],
			upvoteByNodeId: [
				90,
				{
					nodeId: [2, 'ID!'],
				},
			],
			userByNodeId: [
				21,
				{
					nodeId: [2, 'ID!'],
				},
			],
			userPointByNodeId: [
				135,
				{
					nodeId: [2, 'ID!'],
				},
			],
			versionByNodeId: [
				247,
				{
					nodeId: [2, 'ID!'],
				},
			],
			voteByNodeId: [
				100,
				{
					nodeId: [2, 'ID!'],
				},
			],
			worldRecordGlobalByNodeId: [
				95,
				{
					nodeId: [2, 'ID!'],
				},
			],
			__typename: [7],
		},
		Node: {
			nodeId: [2],
			on_Query: [0],
			on_Favorite: [20],
			on_User: [21],
			on_PersonalBestGlobal: [65],
			on_Record: [66],
			on_Level: [67],
			on_LevelItem: [69],
			on_LevelMetadatum: [74],
			on_LevelPoint: [79],
			on_Upvote: [90],
			on_WorldRecordGlobal: [95],
			on_Vote: [100],
			on_RecordMedia: [121],
			on_UserPoint: [135],
			on_LevelRequest: [155],
			on_Version: [247],
			__typename: [7],
		},
		ID: {},
		VersionInfosConnection: {
			nodes: [4],
			edges: [8],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		VersionInfo: {
			version: [5],
			appliedOn: [6],
			description: [7],
			__typename: [7],
		},
		BigInt: {},
		Datetime: {},
		String: {},
		VersionInfosEdge: {
			cursor: [9],
			node: [4],
			__typename: [7],
		},
		Cursor: {},
		PageInfo: {
			hasNextPage: [11],
			hasPreviousPage: [11],
			startCursor: [9],
			endCursor: [9],
			__typename: [7],
		},
		Boolean: {},
		Int: {},
		VersionInfosOrderBy: {},
		VersionInfoCondition: {
			version: [5],
			appliedOn: [6],
			description: [7],
			__typename: [7],
		},
		VersionInfoFilter: {
			version: [16],
			appliedOn: [17],
			description: [18],
			and: [15],
			or: [15],
			not: [15],
			__typename: [7],
		},
		BigIntFilter: {
			isNull: [11],
			equalTo: [5],
			notEqualTo: [5],
			distinctFrom: [5],
			notDistinctFrom: [5],
			in: [5],
			notIn: [5],
			lessThan: [5],
			lessThanOrEqualTo: [5],
			greaterThan: [5],
			greaterThanOrEqualTo: [5],
			__typename: [7],
		},
		DatetimeFilter: {
			isNull: [11],
			equalTo: [6],
			notEqualTo: [6],
			distinctFrom: [6],
			notDistinctFrom: [6],
			in: [6],
			notIn: [6],
			lessThan: [6],
			lessThanOrEqualTo: [6],
			greaterThan: [6],
			greaterThanOrEqualTo: [6],
			__typename: [7],
		},
		StringFilter: {
			isNull: [11],
			equalTo: [7],
			notEqualTo: [7],
			distinctFrom: [7],
			notDistinctFrom: [7],
			in: [7],
			notIn: [7],
			lessThan: [7],
			lessThanOrEqualTo: [7],
			greaterThan: [7],
			greaterThanOrEqualTo: [7],
			includes: [7],
			notIncludes: [7],
			includesInsensitive: [7],
			notIncludesInsensitive: [7],
			startsWith: [7],
			notStartsWith: [7],
			startsWithInsensitive: [7],
			notStartsWithInsensitive: [7],
			endsWith: [7],
			notEndsWith: [7],
			endsWithInsensitive: [7],
			notEndsWithInsensitive: [7],
			like: [7],
			notLike: [7],
			likeInsensitive: [7],
			notLikeInsensitive: [7],
			equalToInsensitive: [7],
			notEqualToInsensitive: [7],
			distinctFromInsensitive: [7],
			notDistinctFromInsensitive: [7],
			inInsensitive: [7],
			notInInsensitive: [7],
			lessThanInsensitive: [7],
			lessThanOrEqualToInsensitive: [7],
			greaterThanInsensitive: [7],
			greaterThanOrEqualToInsensitive: [7],
			__typename: [7],
		},
		FavoritesConnection: {
			nodes: [20],
			edges: [151],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		Favorite: {
			nodeId: [2],
			id: [12],
			userId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			levelId: [12],
			user: [21],
			level: [67],
			__typename: [7],
		},
		User: {
			nodeId: [2],
			id: [12],
			steamName: [7],
			banned: [11],
			dateCreated: [6],
			dateUpdated: [6],
			steamId: [22],
			discordId: [22],
			favorites: [
				19,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [23, '[FavoritesOrderBy!]'],
					condition: [24],
					filter: [25],
				},
			],
			personalBestGlobals: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			userPoints: [
				134,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [137, '[UserPointsOrderBy!]'],
					condition: [138],
					filter: [60],
				},
			],
			records: [
				85,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [87, '[RecordsOrderBy!]'],
					condition: [88],
					filter: [33],
				},
			],
			upvotes: [
				89,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [92, '[UpvotesOrderBy!]'],
					condition: [93],
					filter: [55],
				},
			],
			votes: [
				99,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [102, '[VotesOrderBy!]'],
					condition: [103],
					filter: [58],
				},
			],
			levelsByFavorite: [
				139,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [129, '[LevelsOrderBy!]'],
					condition: [130],
					filter: [42],
				},
			],
			recordsByPersonalBestGlobal: [
				141,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [87, '[RecordsOrderBy!]'],
					condition: [88],
					filter: [33],
				},
			],
			levelsByPersonalBestGlobal: [
				143,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [129, '[LevelsOrderBy!]'],
					condition: [130],
					filter: [42],
				},
			],
			levelsByRecord: [
				145,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [129, '[LevelsOrderBy!]'],
					condition: [130],
					filter: [42],
				},
			],
			levelsByUpvote: [
				147,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [129, '[LevelsOrderBy!]'],
					condition: [130],
					filter: [42],
				},
			],
			levelsByVote: [
				149,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [129, '[LevelsOrderBy!]'],
					condition: [130],
					filter: [42],
				},
			],
			__typename: [7],
		},
		BigFloat: {},
		FavoritesOrderBy: {},
		FavoriteCondition: {
			id: [12],
			userId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			levelId: [12],
			__typename: [7],
		},
		FavoriteFilter: {
			id: [26],
			userId: [26],
			dateCreated: [17],
			dateUpdated: [17],
			levelId: [26],
			user: [27],
			level: [42],
			and: [25],
			or: [25],
			not: [25],
			__typename: [7],
		},
		IntFilter: {
			isNull: [11],
			equalTo: [12],
			notEqualTo: [12],
			distinctFrom: [12],
			notDistinctFrom: [12],
			in: [12],
			notIn: [12],
			lessThan: [12],
			lessThanOrEqualTo: [12],
			greaterThan: [12],
			greaterThanOrEqualTo: [12],
			__typename: [7],
		},
		UserFilter: {
			id: [26],
			steamName: [18],
			banned: [28],
			dateCreated: [17],
			dateUpdated: [17],
			steamId: [29],
			discordId: [29],
			favorites: [30],
			favoritesExist: [11],
			personalBestGlobals: [31],
			personalBestGlobalsExist: [11],
			userPoints: [59],
			userPointsExist: [11],
			records: [61],
			recordsExist: [11],
			upvotes: [62],
			upvotesExist: [11],
			votes: [63],
			votesExist: [11],
			and: [27],
			or: [27],
			not: [27],
			__typename: [7],
		},
		BooleanFilter: {
			isNull: [11],
			equalTo: [11],
			notEqualTo: [11],
			distinctFrom: [11],
			notDistinctFrom: [11],
			in: [11],
			notIn: [11],
			lessThan: [11],
			lessThanOrEqualTo: [11],
			greaterThan: [11],
			greaterThanOrEqualTo: [11],
			__typename: [7],
		},
		BigFloatFilter: {
			isNull: [11],
			equalTo: [22],
			notEqualTo: [22],
			distinctFrom: [22],
			notDistinctFrom: [22],
			in: [22],
			notIn: [22],
			lessThan: [22],
			lessThanOrEqualTo: [22],
			greaterThan: [22],
			greaterThanOrEqualTo: [22],
			__typename: [7],
		},
		UserToManyFavoriteFilter: {
			every: [25],
			some: [25],
			none: [25],
			__typename: [7],
		},
		UserToManyPersonalBestGlobalFilter: {
			every: [32],
			some: [32],
			none: [32],
			__typename: [7],
		},
		PersonalBestGlobalFilter: {
			id: [26],
			recordId: [26],
			userId: [26],
			levelId: [26],
			dateCreated: [17],
			dateUpdated: [17],
			record: [33],
			user: [27],
			level: [42],
			and: [32],
			or: [32],
			not: [32],
			__typename: [7],
		},
		RecordFilter: {
			id: [26],
			userId: [26],
			time: [34],
			gameVersion: [18],
			levelId: [26],
			modVersion: [18],
			dateCreated: [17],
			dateUpdated: [17],
			splits: [36],
			speeds: [36],
			recordMedias: [37],
			recordMediasExist: [11],
			personalBestGlobals: [39],
			personalBestGlobalsExist: [11],
			worldRecordGlobals: [40],
			worldRecordGlobalsExist: [11],
			user: [27],
			level: [42],
			and: [33],
			or: [33],
			not: [33],
			__typename: [7],
		},
		FloatFilter: {
			isNull: [11],
			equalTo: [35],
			notEqualTo: [35],
			distinctFrom: [35],
			notDistinctFrom: [35],
			in: [35],
			notIn: [35],
			lessThan: [35],
			lessThanOrEqualTo: [35],
			greaterThan: [35],
			greaterThanOrEqualTo: [35],
			__typename: [7],
		},
		Float: {},
		FloatListFilter: {
			isNull: [11],
			equalTo: [35],
			notEqualTo: [35],
			distinctFrom: [35],
			notDistinctFrom: [35],
			lessThan: [35],
			lessThanOrEqualTo: [35],
			greaterThan: [35],
			greaterThanOrEqualTo: [35],
			contains: [35],
			containedBy: [35],
			overlaps: [35],
			anyEqualTo: [35],
			anyNotEqualTo: [35],
			anyLessThan: [35],
			anyLessThanOrEqualTo: [35],
			anyGreaterThan: [35],
			anyGreaterThanOrEqualTo: [35],
			__typename: [7],
		},
		RecordToManyRecordMediaFilter: {
			every: [38],
			some: [38],
			none: [38],
			__typename: [7],
		},
		RecordMediaFilter: {
			id: [26],
			recordId: [26],
			ghostUrl: [18],
			dateCreated: [17],
			dateUpdated: [17],
			record: [33],
			and: [38],
			or: [38],
			not: [38],
			__typename: [7],
		},
		RecordToManyPersonalBestGlobalFilter: {
			every: [32],
			some: [32],
			none: [32],
			__typename: [7],
		},
		RecordToManyWorldRecordGlobalFilter: {
			every: [41],
			some: [41],
			none: [41],
			__typename: [7],
		},
		WorldRecordGlobalFilter: {
			id: [26],
			recordId: [26],
			levelId: [26],
			dateCreated: [17],
			dateUpdated: [17],
			record: [33],
			level: [42],
			and: [41],
			or: [41],
			not: [41],
			__typename: [7],
		},
		LevelFilter: {
			id: [26],
			hash: [18],
			dateCreated: [17],
			dateUpdated: [17],
			favorites: [43],
			favoritesExist: [11],
			levelItems: [44],
			levelItemsExist: [11],
			levelMetadata: [46],
			levelMetadataExist: [11],
			levelPoints: [50],
			levelPointsExist: [11],
			personalBestGlobals: [52],
			personalBestGlobalsExist: [11],
			records: [53],
			recordsExist: [11],
			upvotes: [54],
			upvotesExist: [11],
			worldRecordGlobals: [56],
			worldRecordGlobalsExist: [11],
			votes: [57],
			votesExist: [11],
			and: [42],
			or: [42],
			not: [42],
			__typename: [7],
		},
		LevelToManyFavoriteFilter: {
			every: [25],
			some: [25],
			none: [25],
			__typename: [7],
		},
		LevelToManyLevelItemFilter: {
			every: [45],
			some: [45],
			none: [45],
			__typename: [7],
		},
		LevelItemFilter: {
			id: [26],
			levelId: [26],
			workshopId: [29],
			authorId: [29],
			name: [18],
			imageUrl: [18],
			fileAuthor: [18],
			fileUid: [18],
			validationTimeAuthor: [34],
			validationTimeGold: [34],
			validationTimeSilver: [34],
			validationTimeBronze: [34],
			deleted: [28],
			createdAt: [17],
			updatedAt: [17],
			dateCreated: [17],
			dateUpdated: [17],
			level: [42],
			and: [45],
			or: [45],
			not: [45],
			__typename: [7],
		},
		LevelToManyLevelMetadatumFilter: {
			every: [47],
			some: [47],
			none: [47],
			__typename: [7],
		},
		LevelMetadatumFilter: {
			id: [26],
			levelId: [26],
			amountCheckpoints: [26],
			amountFinishes: [26],
			amountBlocks: [26],
			typeGround: [26],
			typeSkybox: [26],
			blocks: [48],
			dateCreated: [17],
			dateUpdated: [17],
			level: [42],
			and: [47],
			or: [47],
			not: [47],
			__typename: [7],
		},
		JSONFilter: {
			isNull: [11],
			equalTo: [49],
			notEqualTo: [49],
			distinctFrom: [49],
			notDistinctFrom: [49],
			in: [49],
			notIn: [49],
			lessThan: [49],
			lessThanOrEqualTo: [49],
			greaterThan: [49],
			greaterThanOrEqualTo: [49],
			contains: [49],
			containsKey: [7],
			containsAllKeys: [7],
			containsAnyKeys: [7],
			containedBy: [49],
			__typename: [7],
		},
		JSON: {},
		LevelToManyLevelPointFilter: {
			every: [51],
			some: [51],
			none: [51],
			__typename: [7],
		},
		LevelPointFilter: {
			id: [26],
			points: [26],
			levelId: [26],
			dateCreated: [17],
			dateUpdated: [17],
			level: [42],
			and: [51],
			or: [51],
			not: [51],
			__typename: [7],
		},
		LevelToManyPersonalBestGlobalFilter: {
			every: [32],
			some: [32],
			none: [32],
			__typename: [7],
		},
		LevelToManyRecordFilter: {
			every: [33],
			some: [33],
			none: [33],
			__typename: [7],
		},
		LevelToManyUpvoteFilter: {
			every: [55],
			some: [55],
			none: [55],
			__typename: [7],
		},
		UpvoteFilter: {
			id: [26],
			userId: [26],
			levelId: [26],
			dateCreated: [17],
			dateUpdated: [17],
			user: [27],
			level: [42],
			and: [55],
			or: [55],
			not: [55],
			__typename: [7],
		},
		LevelToManyWorldRecordGlobalFilter: {
			every: [41],
			some: [41],
			none: [41],
			__typename: [7],
		},
		LevelToManyVoteFilter: {
			every: [58],
			some: [58],
			none: [58],
			__typename: [7],
		},
		VoteFilter: {
			id: [26],
			userId: [26],
			levelId: [26],
			value: [26],
			dateCreated: [17],
			dateUpdated: [17],
			user: [27],
			level: [42],
			and: [58],
			or: [58],
			not: [58],
			__typename: [7],
		},
		UserToManyUserPointFilter: {
			every: [60],
			some: [60],
			none: [60],
			__typename: [7],
		},
		UserPointFilter: {
			id: [26],
			userId: [26],
			points: [26],
			dateCreated: [17],
			dateUpdated: [17],
			rank: [26],
			worldRecords: [26],
			user: [27],
			and: [60],
			or: [60],
			not: [60],
			__typename: [7],
		},
		UserToManyRecordFilter: {
			every: [33],
			some: [33],
			none: [33],
			__typename: [7],
		},
		UserToManyUpvoteFilter: {
			every: [55],
			some: [55],
			none: [55],
			__typename: [7],
		},
		UserToManyVoteFilter: {
			every: [58],
			some: [58],
			none: [58],
			__typename: [7],
		},
		PersonalBestGlobalsConnection: {
			nodes: [65],
			edges: [133],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		PersonalBestGlobal: {
			nodeId: [2],
			id: [12],
			recordId: [12],
			userId: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			record: [66],
			user: [21],
			level: [67],
			__typename: [7],
		},
		Record: {
			nodeId: [2],
			id: [12],
			userId: [12],
			time: [35],
			gameVersion: [7],
			levelId: [12],
			modVersion: [7],
			dateCreated: [6],
			dateUpdated: [6],
			splits: [35],
			speeds: [35],
			user: [21],
			level: [67],
			recordMedias: [
				120,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [123, '[RecordMediaOrderBy!]'],
					condition: [124],
					filter: [38],
				},
			],
			personalBestGlobals: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			worldRecordGlobals: [
				94,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [97, '[WorldRecordGlobalsOrderBy!]'],
					condition: [98],
					filter: [41],
				},
			],
			usersByPersonalBestGlobal: [
				125,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [106, '[UsersOrderBy!]'],
					condition: [107],
					filter: [27],
				},
			],
			levelsByPersonalBestGlobal: [
				127,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [129, '[LevelsOrderBy!]'],
					condition: [130],
					filter: [42],
				},
			],
			levelsByWorldRecordGlobal: [
				131,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [129, '[LevelsOrderBy!]'],
					condition: [130],
					filter: [42],
				},
			],
			__typename: [7],
		},
		Level: {
			nodeId: [2],
			id: [12],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			favorites: [
				19,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [23, '[FavoritesOrderBy!]'],
					condition: [24],
					filter: [25],
				},
			],
			levelItems: [
				68,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [71, '[LevelItemsOrderBy!]'],
					condition: [72],
					filter: [45],
				},
			],
			levelMetadata: [
				73,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [76, '[LevelMetadataOrderBy!]'],
					condition: [77],
					filter: [47],
				},
			],
			levelPoints: [
				78,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [81, '[LevelPointsOrderBy!]'],
					condition: [82],
					filter: [51],
				},
			],
			personalBestGlobals: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			records: [
				85,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [87, '[RecordsOrderBy!]'],
					condition: [88],
					filter: [33],
				},
			],
			upvotes: [
				89,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [92, '[UpvotesOrderBy!]'],
					condition: [93],
					filter: [55],
				},
			],
			worldRecordGlobals: [
				94,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [97, '[WorldRecordGlobalsOrderBy!]'],
					condition: [98],
					filter: [41],
				},
			],
			votes: [
				99,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [102, '[VotesOrderBy!]'],
					condition: [103],
					filter: [58],
				},
			],
			usersByFavorite: [
				104,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [106, '[UsersOrderBy!]'],
					condition: [107],
					filter: [27],
				},
			],
			recordsByPersonalBestGlobal: [
				108,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [87, '[RecordsOrderBy!]'],
					condition: [88],
					filter: [33],
				},
			],
			usersByPersonalBestGlobal: [
				110,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [106, '[UsersOrderBy!]'],
					condition: [107],
					filter: [27],
				},
			],
			usersByRecord: [
				112,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [106, '[UsersOrderBy!]'],
					condition: [107],
					filter: [27],
				},
			],
			usersByUpvote: [
				114,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [106, '[UsersOrderBy!]'],
					condition: [107],
					filter: [27],
				},
			],
			recordsByWorldRecordGlobal: [
				116,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [87, '[RecordsOrderBy!]'],
					condition: [88],
					filter: [33],
				},
			],
			usersByVote: [
				118,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [106, '[UsersOrderBy!]'],
					condition: [107],
					filter: [27],
				},
			],
			__typename: [7],
		},
		LevelItemsConnection: {
			nodes: [69],
			edges: [70],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelItem: {
			nodeId: [2],
			id: [12],
			levelId: [12],
			workshopId: [22],
			authorId: [22],
			name: [7],
			imageUrl: [7],
			fileAuthor: [7],
			fileUid: [7],
			validationTimeAuthor: [35],
			validationTimeGold: [35],
			validationTimeSilver: [35],
			validationTimeBronze: [35],
			deleted: [11],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			level: [67],
			__typename: [7],
		},
		LevelItemsEdge: {
			cursor: [9],
			node: [69],
			__typename: [7],
		},
		LevelItemsOrderBy: {},
		LevelItemCondition: {
			id: [12],
			levelId: [12],
			workshopId: [22],
			authorId: [22],
			name: [7],
			imageUrl: [7],
			fileAuthor: [7],
			fileUid: [7],
			validationTimeAuthor: [35],
			validationTimeGold: [35],
			validationTimeSilver: [35],
			validationTimeBronze: [35],
			deleted: [11],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelMetadataConnection: {
			nodes: [74],
			edges: [75],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelMetadatum: {
			nodeId: [2],
			id: [12],
			levelId: [12],
			amountCheckpoints: [12],
			amountFinishes: [12],
			amountBlocks: [12],
			typeGround: [12],
			typeSkybox: [12],
			blocks: [49],
			dateCreated: [6],
			dateUpdated: [6],
			level: [67],
			__typename: [7],
		},
		LevelMetadataEdge: {
			cursor: [9],
			node: [74],
			__typename: [7],
		},
		LevelMetadataOrderBy: {},
		LevelMetadatumCondition: {
			id: [12],
			levelId: [12],
			amountCheckpoints: [12],
			amountFinishes: [12],
			amountBlocks: [12],
			typeGround: [12],
			typeSkybox: [12],
			blocks: [49],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelPointsConnection: {
			nodes: [79],
			edges: [80],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelPoint: {
			nodeId: [2],
			id: [12],
			points: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			level: [67],
			__typename: [7],
		},
		LevelPointsEdge: {
			cursor: [9],
			node: [79],
			__typename: [7],
		},
		LevelPointsOrderBy: {},
		LevelPointCondition: {
			id: [12],
			points: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		PersonalBestGlobalsOrderBy: {},
		PersonalBestGlobalCondition: {
			id: [12],
			recordId: [12],
			userId: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		RecordsConnection: {
			nodes: [66],
			edges: [86],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		RecordsEdge: {
			cursor: [9],
			node: [66],
			__typename: [7],
		},
		RecordsOrderBy: {},
		RecordCondition: {
			id: [12],
			userId: [12],
			time: [35],
			gameVersion: [7],
			levelId: [12],
			modVersion: [7],
			dateCreated: [6],
			dateUpdated: [6],
			splits: [35],
			speeds: [35],
			__typename: [7],
		},
		UpvotesConnection: {
			nodes: [90],
			edges: [91],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		Upvote: {
			nodeId: [2],
			id: [12],
			userId: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			user: [21],
			level: [67],
			__typename: [7],
		},
		UpvotesEdge: {
			cursor: [9],
			node: [90],
			__typename: [7],
		},
		UpvotesOrderBy: {},
		UpvoteCondition: {
			id: [12],
			userId: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		WorldRecordGlobalsConnection: {
			nodes: [95],
			edges: [96],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		WorldRecordGlobal: {
			nodeId: [2],
			id: [12],
			recordId: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			record: [66],
			level: [67],
			__typename: [7],
		},
		WorldRecordGlobalsEdge: {
			cursor: [9],
			node: [95],
			__typename: [7],
		},
		WorldRecordGlobalsOrderBy: {},
		WorldRecordGlobalCondition: {
			id: [12],
			recordId: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		VotesConnection: {
			nodes: [100],
			edges: [101],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		Vote: {
			nodeId: [2],
			id: [12],
			userId: [12],
			levelId: [12],
			value: [12],
			dateCreated: [6],
			dateUpdated: [6],
			user: [21],
			level: [67],
			__typename: [7],
		},
		VotesEdge: {
			cursor: [9],
			node: [100],
			__typename: [7],
		},
		VotesOrderBy: {},
		VoteCondition: {
			id: [12],
			userId: [12],
			levelId: [12],
			value: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelUsersByFavoriteManyToManyConnection: {
			nodes: [21],
			edges: [105],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelUsersByFavoriteManyToManyEdge: {
			cursor: [9],
			node: [21],
			favorites: [
				19,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [23, '[FavoritesOrderBy!]'],
					condition: [24],
					filter: [25],
				},
			],
			__typename: [7],
		},
		UsersOrderBy: {},
		UserCondition: {
			id: [12],
			steamName: [7],
			banned: [11],
			dateCreated: [6],
			dateUpdated: [6],
			steamId: [22],
			discordId: [22],
			__typename: [7],
		},
		LevelRecordsByPersonalBestGlobalManyToManyConnection: {
			nodes: [66],
			edges: [109],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelRecordsByPersonalBestGlobalManyToManyEdge: {
			cursor: [9],
			node: [66],
			personalBestGlobals: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			__typename: [7],
		},
		LevelUsersByPersonalBestGlobalManyToManyConnection: {
			nodes: [21],
			edges: [111],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelUsersByPersonalBestGlobalManyToManyEdge: {
			cursor: [9],
			node: [21],
			personalBestGlobals: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			__typename: [7],
		},
		LevelUsersByRecordManyToManyConnection: {
			nodes: [21],
			edges: [113],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelUsersByRecordManyToManyEdge: {
			cursor: [9],
			node: [21],
			records: [
				85,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [87, '[RecordsOrderBy!]'],
					condition: [88],
					filter: [33],
				},
			],
			__typename: [7],
		},
		LevelUsersByUpvoteManyToManyConnection: {
			nodes: [21],
			edges: [115],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelUsersByUpvoteManyToManyEdge: {
			cursor: [9],
			node: [21],
			upvotes: [
				89,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [92, '[UpvotesOrderBy!]'],
					condition: [93],
					filter: [55],
				},
			],
			__typename: [7],
		},
		LevelRecordsByWorldRecordGlobalManyToManyConnection: {
			nodes: [66],
			edges: [117],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelRecordsByWorldRecordGlobalManyToManyEdge: {
			cursor: [9],
			node: [66],
			worldRecordGlobals: [
				94,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [97, '[WorldRecordGlobalsOrderBy!]'],
					condition: [98],
					filter: [41],
				},
			],
			__typename: [7],
		},
		LevelUsersByVoteManyToManyConnection: {
			nodes: [21],
			edges: [119],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelUsersByVoteManyToManyEdge: {
			cursor: [9],
			node: [21],
			votes: [
				99,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [102, '[VotesOrderBy!]'],
					condition: [103],
					filter: [58],
				},
			],
			__typename: [7],
		},
		RecordMediaConnection: {
			nodes: [121],
			edges: [122],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		RecordMedia: {
			nodeId: [2],
			id: [12],
			recordId: [12],
			ghostUrl: [7],
			dateCreated: [6],
			dateUpdated: [6],
			record: [66],
			__typename: [7],
		},
		RecordMediaEdge: {
			cursor: [9],
			node: [121],
			__typename: [7],
		},
		RecordMediaOrderBy: {},
		RecordMediaCondition: {
			id: [12],
			recordId: [12],
			ghostUrl: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		RecordUsersByPersonalBestGlobalManyToManyConnection: {
			nodes: [21],
			edges: [126],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		RecordUsersByPersonalBestGlobalManyToManyEdge: {
			cursor: [9],
			node: [21],
			personalBestGlobals: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			__typename: [7],
		},
		RecordLevelsByPersonalBestGlobalManyToManyConnection: {
			nodes: [67],
			edges: [128],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		RecordLevelsByPersonalBestGlobalManyToManyEdge: {
			cursor: [9],
			node: [67],
			personalBestGlobals: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			__typename: [7],
		},
		LevelsOrderBy: {},
		LevelCondition: {
			id: [12],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		RecordLevelsByWorldRecordGlobalManyToManyConnection: {
			nodes: [67],
			edges: [132],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		RecordLevelsByWorldRecordGlobalManyToManyEdge: {
			cursor: [9],
			node: [67],
			worldRecordGlobals: [
				94,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [97, '[WorldRecordGlobalsOrderBy!]'],
					condition: [98],
					filter: [41],
				},
			],
			__typename: [7],
		},
		PersonalBestGlobalsEdge: {
			cursor: [9],
			node: [65],
			__typename: [7],
		},
		UserPointsConnection: {
			nodes: [135],
			edges: [136],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		UserPoint: {
			nodeId: [2],
			id: [12],
			userId: [12],
			points: [12],
			dateCreated: [6],
			dateUpdated: [6],
			rank: [12],
			worldRecords: [12],
			user: [21],
			__typename: [7],
		},
		UserPointsEdge: {
			cursor: [9],
			node: [135],
			__typename: [7],
		},
		UserPointsOrderBy: {},
		UserPointCondition: {
			id: [12],
			userId: [12],
			points: [12],
			dateCreated: [6],
			dateUpdated: [6],
			rank: [12],
			worldRecords: [12],
			__typename: [7],
		},
		UserLevelsByFavoriteManyToManyConnection: {
			nodes: [67],
			edges: [140],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		UserLevelsByFavoriteManyToManyEdge: {
			cursor: [9],
			node: [67],
			favorites: [
				19,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [23, '[FavoritesOrderBy!]'],
					condition: [24],
					filter: [25],
				},
			],
			__typename: [7],
		},
		UserRecordsByPersonalBestGlobalManyToManyConnection: {
			nodes: [66],
			edges: [142],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		UserRecordsByPersonalBestGlobalManyToManyEdge: {
			cursor: [9],
			node: [66],
			personalBestGlobals: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			__typename: [7],
		},
		UserLevelsByPersonalBestGlobalManyToManyConnection: {
			nodes: [67],
			edges: [144],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		UserLevelsByPersonalBestGlobalManyToManyEdge: {
			cursor: [9],
			node: [67],
			personalBestGlobals: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			__typename: [7],
		},
		UserLevelsByRecordManyToManyConnection: {
			nodes: [67],
			edges: [146],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		UserLevelsByRecordManyToManyEdge: {
			cursor: [9],
			node: [67],
			records: [
				85,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [87, '[RecordsOrderBy!]'],
					condition: [88],
					filter: [33],
				},
			],
			__typename: [7],
		},
		UserLevelsByUpvoteManyToManyConnection: {
			nodes: [67],
			edges: [148],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		UserLevelsByUpvoteManyToManyEdge: {
			cursor: [9],
			node: [67],
			upvotes: [
				89,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [92, '[UpvotesOrderBy!]'],
					condition: [93],
					filter: [55],
				},
			],
			__typename: [7],
		},
		UserLevelsByVoteManyToManyConnection: {
			nodes: [67],
			edges: [150],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		UserLevelsByVoteManyToManyEdge: {
			cursor: [9],
			node: [67],
			votes: [
				99,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [102, '[VotesOrderBy!]'],
					condition: [103],
					filter: [58],
				},
			],
			__typename: [7],
		},
		FavoritesEdge: {
			cursor: [9],
			node: [20],
			__typename: [7],
		},
		LevelsConnection: {
			nodes: [67],
			edges: [153],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelsEdge: {
			cursor: [9],
			node: [67],
			__typename: [7],
		},
		LevelRequestsConnection: {
			nodes: [155],
			edges: [156],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelRequest: {
			nodeId: [2],
			id: [12],
			workshopId: [22],
			uid: [7],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelRequestsEdge: {
			cursor: [9],
			node: [155],
			__typename: [7],
		},
		LevelRequestsOrderBy: {},
		LevelRequestCondition: {
			id: [12],
			workshopId: [22],
			uid: [7],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelRequestFilter: {
			id: [26],
			workshopId: [29],
			uid: [18],
			hash: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [159],
			or: [159],
			not: [159],
			__typename: [7],
		},
		SampledFavoritesConnection: {
			nodes: [161],
			edges: [162],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledFavorite: {
			id: [12],
			userId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			levelId: [12],
			__typename: [7],
		},
		SampledFavoritesEdge: {
			cursor: [9],
			node: [161],
			__typename: [7],
		},
		SampledFavoritesOrderBy: {},
		SampledFavoriteCondition: {
			id: [12],
			userId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			levelId: [12],
			__typename: [7],
		},
		SampledFavoriteFilter: {
			id: [26],
			userId: [26],
			dateCreated: [17],
			dateUpdated: [17],
			levelId: [26],
			and: [165],
			or: [165],
			not: [165],
			__typename: [7],
		},
		SampledLevelsConnection: {
			nodes: [167],
			edges: [168],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledLevel: {
			id: [12],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelsEdge: {
			cursor: [9],
			node: [167],
			__typename: [7],
		},
		SampledLevelsOrderBy: {},
		SampledLevelCondition: {
			id: [12],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelFilter: {
			id: [26],
			hash: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [171],
			or: [171],
			not: [171],
			__typename: [7],
		},
		SampledLevelItemsConnection: {
			nodes: [173],
			edges: [174],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledLevelItem: {
			id: [12],
			levelId: [12],
			workshopId: [22],
			authorId: [22],
			name: [7],
			imageUrl: [7],
			fileAuthor: [7],
			fileUid: [7],
			validationTimeAuthor: [35],
			validationTimeGold: [35],
			validationTimeSilver: [35],
			validationTimeBronze: [35],
			deleted: [11],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelItemsEdge: {
			cursor: [9],
			node: [173],
			__typename: [7],
		},
		SampledLevelItemsOrderBy: {},
		SampledLevelItemCondition: {
			id: [12],
			levelId: [12],
			workshopId: [22],
			authorId: [22],
			name: [7],
			imageUrl: [7],
			fileAuthor: [7],
			fileUid: [7],
			validationTimeAuthor: [35],
			validationTimeGold: [35],
			validationTimeSilver: [35],
			validationTimeBronze: [35],
			deleted: [11],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelItemFilter: {
			id: [26],
			levelId: [26],
			workshopId: [29],
			authorId: [29],
			name: [18],
			imageUrl: [18],
			fileAuthor: [18],
			fileUid: [18],
			validationTimeAuthor: [34],
			validationTimeGold: [34],
			validationTimeSilver: [34],
			validationTimeBronze: [34],
			deleted: [28],
			createdAt: [17],
			updatedAt: [17],
			dateCreated: [17],
			dateUpdated: [17],
			and: [177],
			or: [177],
			not: [177],
			__typename: [7],
		},
		SampledLevelMetadataConnection: {
			nodes: [179],
			edges: [180],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledLevelMetadatum: {
			id: [12],
			levelId: [12],
			amountCheckpoints: [12],
			amountFinishes: [12],
			amountBlocks: [12],
			typeGround: [12],
			typeSkybox: [12],
			blocks: [49],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelMetadataEdge: {
			cursor: [9],
			node: [179],
			__typename: [7],
		},
		SampledLevelMetadataOrderBy: {},
		SampledLevelMetadatumCondition: {
			id: [12],
			levelId: [12],
			amountCheckpoints: [12],
			amountFinishes: [12],
			amountBlocks: [12],
			typeGround: [12],
			typeSkybox: [12],
			blocks: [49],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelMetadatumFilter: {
			id: [26],
			levelId: [26],
			amountCheckpoints: [26],
			amountFinishes: [26],
			amountBlocks: [26],
			typeGround: [26],
			typeSkybox: [26],
			blocks: [48],
			dateCreated: [17],
			dateUpdated: [17],
			and: [183],
			or: [183],
			not: [183],
			__typename: [7],
		},
		SampledLevelPointsConnection: {
			nodes: [185],
			edges: [186],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledLevelPoint: {
			id: [12],
			points: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelPointsEdge: {
			cursor: [9],
			node: [185],
			__typename: [7],
		},
		SampledLevelPointsOrderBy: {},
		SampledLevelPointCondition: {
			id: [12],
			points: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelPointFilter: {
			id: [26],
			points: [26],
			levelId: [26],
			dateCreated: [17],
			dateUpdated: [17],
			and: [189],
			or: [189],
			not: [189],
			__typename: [7],
		},
		SampledLevelRequestsConnection: {
			nodes: [191],
			edges: [192],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledLevelRequest: {
			id: [12],
			workshopId: [22],
			uid: [7],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelRequestsEdge: {
			cursor: [9],
			node: [191],
			__typename: [7],
		},
		SampledLevelRequestsOrderBy: {},
		SampledLevelRequestCondition: {
			id: [12],
			workshopId: [22],
			uid: [7],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelRequestFilter: {
			id: [26],
			workshopId: [29],
			uid: [18],
			hash: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [195],
			or: [195],
			not: [195],
			__typename: [7],
		},
		SampledPersonalBestGlobalsConnection: {
			nodes: [197],
			edges: [198],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledPersonalBestGlobal: {
			id: [12],
			recordId: [12],
			userId: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledPersonalBestGlobalsEdge: {
			cursor: [9],
			node: [197],
			__typename: [7],
		},
		SampledPersonalBestGlobalsOrderBy: {},
		SampledPersonalBestGlobalCondition: {
			id: [12],
			recordId: [12],
			userId: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledPersonalBestGlobalFilter: {
			id: [26],
			recordId: [26],
			userId: [26],
			levelId: [26],
			dateCreated: [17],
			dateUpdated: [17],
			and: [201],
			or: [201],
			not: [201],
			__typename: [7],
		},
		SampledRecordsConnection: {
			nodes: [203],
			edges: [204],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledRecord: {
			id: [12],
			userId: [12],
			time: [35],
			gameVersion: [7],
			levelId: [12],
			modVersion: [7],
			dateCreated: [6],
			dateUpdated: [6],
			splits: [35],
			speeds: [35],
			__typename: [7],
		},
		SampledRecordsEdge: {
			cursor: [9],
			node: [203],
			__typename: [7],
		},
		SampledRecordsOrderBy: {},
		SampledRecordCondition: {
			id: [12],
			userId: [12],
			time: [35],
			gameVersion: [7],
			levelId: [12],
			modVersion: [7],
			dateCreated: [6],
			dateUpdated: [6],
			splits: [35],
			speeds: [35],
			__typename: [7],
		},
		SampledRecordFilter: {
			id: [26],
			userId: [26],
			time: [34],
			gameVersion: [18],
			levelId: [26],
			modVersion: [18],
			dateCreated: [17],
			dateUpdated: [17],
			splits: [36],
			speeds: [36],
			and: [207],
			or: [207],
			not: [207],
			__typename: [7],
		},
		SampledRecordMediaConnection: {
			nodes: [209],
			edges: [210],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledRecordMedia: {
			id: [12],
			recordId: [12],
			ghostUrl: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledRecordMediaEdge: {
			cursor: [9],
			node: [209],
			__typename: [7],
		},
		SampledRecordMediaOrderBy: {},
		SampledRecordMediaCondition: {
			id: [12],
			recordId: [12],
			ghostUrl: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledRecordMediaFilter: {
			id: [26],
			recordId: [26],
			ghostUrl: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [213],
			or: [213],
			not: [213],
			__typename: [7],
		},
		SampledUpvotesConnection: {
			nodes: [215],
			edges: [216],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledUpvote: {
			id: [12],
			userId: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledUpvotesEdge: {
			cursor: [9],
			node: [215],
			__typename: [7],
		},
		SampledUpvotesOrderBy: {},
		SampledUpvoteCondition: {
			id: [12],
			userId: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledUpvoteFilter: {
			id: [26],
			userId: [26],
			levelId: [26],
			dateCreated: [17],
			dateUpdated: [17],
			and: [219],
			or: [219],
			not: [219],
			__typename: [7],
		},
		SampledUsersConnection: {
			nodes: [221],
			edges: [222],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledUser: {
			id: [12],
			steamName: [7],
			banned: [11],
			dateCreated: [6],
			dateUpdated: [6],
			steamId: [22],
			discordId: [22],
			__typename: [7],
		},
		SampledUsersEdge: {
			cursor: [9],
			node: [221],
			__typename: [7],
		},
		SampledUsersOrderBy: {},
		SampledUserCondition: {
			id: [12],
			steamName: [7],
			banned: [11],
			dateCreated: [6],
			dateUpdated: [6],
			steamId: [22],
			discordId: [22],
			__typename: [7],
		},
		SampledUserFilter: {
			id: [26],
			steamName: [18],
			banned: [28],
			dateCreated: [17],
			dateUpdated: [17],
			steamId: [29],
			discordId: [29],
			and: [225],
			or: [225],
			not: [225],
			__typename: [7],
		},
		SampledUserPointsConnection: {
			nodes: [227],
			edges: [228],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledUserPoint: {
			id: [12],
			userId: [12],
			points: [12],
			dateCreated: [6],
			dateUpdated: [6],
			rank: [12],
			worldRecords: [12],
			__typename: [7],
		},
		SampledUserPointsEdge: {
			cursor: [9],
			node: [227],
			__typename: [7],
		},
		SampledUserPointsOrderBy: {},
		SampledUserPointCondition: {
			id: [12],
			userId: [12],
			points: [12],
			dateCreated: [6],
			dateUpdated: [6],
			rank: [12],
			worldRecords: [12],
			__typename: [7],
		},
		SampledUserPointFilter: {
			id: [26],
			userId: [26],
			points: [26],
			dateCreated: [17],
			dateUpdated: [17],
			rank: [26],
			worldRecords: [26],
			and: [231],
			or: [231],
			not: [231],
			__typename: [7],
		},
		SampledVersionsConnection: {
			nodes: [233],
			edges: [234],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledVersion: {
			id: [12],
			minimum: [7],
			latest: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledVersionsEdge: {
			cursor: [9],
			node: [233],
			__typename: [7],
		},
		SampledVersionsOrderBy: {},
		SampledVersionCondition: {
			id: [12],
			minimum: [7],
			latest: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledVersionFilter: {
			id: [26],
			minimum: [18],
			latest: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [237],
			or: [237],
			not: [237],
			__typename: [7],
		},
		SampledWorldRecordGlobalsConnection: {
			nodes: [239],
			edges: [240],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledWorldRecordGlobal: {
			id: [12],
			recordId: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledWorldRecordGlobalsEdge: {
			cursor: [9],
			node: [239],
			__typename: [7],
		},
		SampledWorldRecordGlobalsOrderBy: {},
		SampledWorldRecordGlobalCondition: {
			id: [12],
			recordId: [12],
			levelId: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledWorldRecordGlobalFilter: {
			id: [26],
			recordId: [26],
			levelId: [26],
			dateCreated: [17],
			dateUpdated: [17],
			and: [243],
			or: [243],
			not: [243],
			__typename: [7],
		},
		UsersConnection: {
			nodes: [21],
			edges: [245],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		UsersEdge: {
			cursor: [9],
			node: [21],
			__typename: [7],
		},
		VersionsConnection: {
			nodes: [247],
			edges: [248],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		Version: {
			nodeId: [2],
			id: [12],
			minimum: [7],
			latest: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		VersionsEdge: {
			cursor: [9],
			node: [247],
			__typename: [7],
		},
		VersionsOrderBy: {},
		VersionCondition: {
			id: [12],
			minimum: [7],
			latest: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		VersionFilter: {
			id: [26],
			minimum: [18],
			latest: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [251],
			or: [251],
			not: [251],
			__typename: [7],
		},
		ZRtmConnection: {
			nodes: [253],
			edges: [254],
			totalCount: [12],
			__typename: [7],
		},
		ZRtmRecord: {
			id: [12],
			idLevel: [12],
			workshopId: [22],
			authorId: [22],
			name: [7],
			imageUrl: [7],
			fileAuthor: [7],
			fileUid: [7],
			validationTimeAuthor: [35],
			validationTimeGold: [35],
			validationTimeSilver: [35],
			validationTimeBronze: [35],
			deleted: [11],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			amountCheckpoints: [12],
			amountFinishes: [12],
			amountBlocks: [12],
			numRecords: [5],
			__typename: [7],
		},
		ZRtmEdge: {
			cursor: [9],
			node: [253],
			__typename: [7],
		},
		ZRtmRecordFilter: {
			id: [26],
			idLevel: [26],
			workshopId: [29],
			authorId: [29],
			name: [18],
			imageUrl: [18],
			fileAuthor: [18],
			fileUid: [18],
			validationTimeAuthor: [34],
			validationTimeGold: [34],
			validationTimeSilver: [34],
			validationTimeBronze: [34],
			deleted: [28],
			createdAt: [17],
			updatedAt: [17],
			dateCreated: [17],
			dateUpdated: [17],
			amountCheckpoints: [26],
			amountFinishes: [26],
			amountBlocks: [26],
			numRecords: [16],
			and: [255],
			or: [255],
			not: [255],
			__typename: [7],
		},
		Mutation: {
			updateWorldRecordGlobal: [
				257,
				{
					input: [258, 'UpdateWorldRecordGlobalInput!'],
				},
			],
			__typename: [7],
		},
		UpdateWorldRecordGlobalPayload: {
			clientMutationId: [7],
			query: [0],
			__typename: [7],
		},
		UpdateWorldRecordGlobalInput: {
			clientMutationId: [7],
			__typename: [7],
		},
		Subscription: {
			query: [0],
			nodeId: [2],
			node: [
				1,
				{
					nodeId: [2, 'ID!'],
				},
			],
			versionInfos: [
				3,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [13, '[VersionInfosOrderBy!]'],
					condition: [14],
					filter: [15],
				},
			],
			favorites: [
				19,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [23, '[FavoritesOrderBy!]'],
					condition: [24],
					filter: [25],
				},
			],
			levels: [
				152,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [129, '[LevelsOrderBy!]'],
					condition: [130],
					filter: [42],
				},
			],
			levelItems: [
				68,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [71, '[LevelItemsOrderBy!]'],
					condition: [72],
					filter: [45],
				},
			],
			levelMetadata: [
				73,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [76, '[LevelMetadataOrderBy!]'],
					condition: [77],
					filter: [47],
				},
			],
			levelPoints: [
				78,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [81, '[LevelPointsOrderBy!]'],
					condition: [82],
					filter: [51],
				},
			],
			levelRequests: [
				154,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [157, '[LevelRequestsOrderBy!]'],
					condition: [158],
					filter: [159],
				},
			],
			personalBestGlobals: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			records: [
				85,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [87, '[RecordsOrderBy!]'],
					condition: [88],
					filter: [33],
				},
			],
			recordMedias: [
				120,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [123, '[RecordMediaOrderBy!]'],
					condition: [124],
					filter: [38],
				},
			],
			sampledFavorites: [
				160,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [163, '[SampledFavoritesOrderBy!]'],
					condition: [164],
					filter: [165],
				},
			],
			sampledLevels: [
				166,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [169, '[SampledLevelsOrderBy!]'],
					condition: [170],
					filter: [171],
				},
			],
			sampledLevelItems: [
				172,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [175, '[SampledLevelItemsOrderBy!]'],
					condition: [176],
					filter: [177],
				},
			],
			sampledLevelMetadata: [
				178,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [181, '[SampledLevelMetadataOrderBy!]'],
					condition: [182],
					filter: [183],
				},
			],
			sampledLevelPoints: [
				184,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [187, '[SampledLevelPointsOrderBy!]'],
					condition: [188],
					filter: [189],
				},
			],
			sampledLevelRequests: [
				190,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [193, '[SampledLevelRequestsOrderBy!]'],
					condition: [194],
					filter: [195],
				},
			],
			sampledPersonalBestGlobals: [
				196,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [199, '[SampledPersonalBestGlobalsOrderBy!]'],
					condition: [200],
					filter: [201],
				},
			],
			sampledRecords: [
				202,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [205, '[SampledRecordsOrderBy!]'],
					condition: [206],
					filter: [207],
				},
			],
			sampledRecordMedias: [
				208,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [211, '[SampledRecordMediaOrderBy!]'],
					condition: [212],
					filter: [213],
				},
			],
			sampledUpvotes: [
				214,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [217, '[SampledUpvotesOrderBy!]'],
					condition: [218],
					filter: [219],
				},
			],
			sampledUsers: [
				220,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [223, '[SampledUsersOrderBy!]'],
					condition: [224],
					filter: [225],
				},
			],
			sampledUserPoints: [
				226,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [229, '[SampledUserPointsOrderBy!]'],
					condition: [230],
					filter: [231],
				},
			],
			sampledVersions: [
				232,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [235, '[SampledVersionsOrderBy!]'],
					condition: [236],
					filter: [237],
				},
			],
			sampledWorldRecordGlobals: [
				238,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [241, '[SampledWorldRecordGlobalsOrderBy!]'],
					condition: [242],
					filter: [243],
				},
			],
			upvotes: [
				89,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [92, '[UpvotesOrderBy!]'],
					condition: [93],
					filter: [55],
				},
			],
			users: [
				244,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [106, '[UsersOrderBy!]'],
					condition: [107],
					filter: [27],
				},
			],
			userPoints: [
				134,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [137, '[UserPointsOrderBy!]'],
					condition: [138],
					filter: [60],
				},
			],
			versions: [
				246,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [249, '[VersionsOrderBy!]'],
					condition: [250],
					filter: [251],
				},
			],
			votes: [
				99,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [102, '[VotesOrderBy!]'],
					condition: [103],
					filter: [58],
				},
			],
			worldRecordGlobals: [
				94,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [97, '[WorldRecordGlobalsOrderBy!]'],
					condition: [98],
					filter: [41],
				},
			],
			favorite: [
				20,
				{
					id: [12, 'Int!'],
				},
			],
			level: [
				67,
				{
					id: [12, 'Int!'],
				},
			],
			levelByHash: [
				67,
				{
					hash: [7, 'String!'],
				},
			],
			levelItem: [
				69,
				{
					id: [12, 'Int!'],
				},
			],
			levelMetadatum: [
				74,
				{
					id: [12, 'Int!'],
				},
			],
			levelPoint: [
				79,
				{
					id: [12, 'Int!'],
				},
			],
			levelRequest: [
				155,
				{
					id: [12, 'Int!'],
				},
			],
			personalBestGlobal: [
				65,
				{
					id: [12, 'Int!'],
				},
			],
			record: [
				66,
				{
					id: [12, 'Int!'],
				},
			],
			recordMedia: [
				121,
				{
					id: [12, 'Int!'],
				},
			],
			upvote: [
				90,
				{
					id: [12, 'Int!'],
				},
			],
			user: [
				21,
				{
					id: [12, 'Int!'],
				},
			],
			userPoint: [
				135,
				{
					id: [12, 'Int!'],
				},
			],
			version: [
				247,
				{
					id: [12, 'Int!'],
				},
			],
			vote: [
				100,
				{
					id: [12, 'Int!'],
				},
			],
			worldRecordGlobal: [
				95,
				{
					id: [12, 'Int!'],
				},
			],
			zRtm: [
				252,
				{
					pMinAuthorTime: [35],
					pMaxAuthorTime: [35],
					pMinRecords: [12],
					pMaxRecords: [12],
					pExcludedAuthorIds: [12, '[Int]'],
					pExcludedHashes: [7, '[String]'],
					pMinCheckpoints: [12],
					pMaxCheckpoints: [12],
					pMinFinishes: [12],
					pMaxFinishes: [12],
					pMinBlocks: [12],
					pMaxBlocks: [12],
					pSampleSize: [12],
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					filter: [255],
				},
			],
			favoriteByNodeId: [
				20,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelByNodeId: [
				67,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelItemByNodeId: [
				69,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelMetadatumByNodeId: [
				74,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelPointByNodeId: [
				79,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelRequestByNodeId: [
				155,
				{
					nodeId: [2, 'ID!'],
				},
			],
			personalBestGlobalByNodeId: [
				65,
				{
					nodeId: [2, 'ID!'],
				},
			],
			recordByNodeId: [
				66,
				{
					nodeId: [2, 'ID!'],
				},
			],
			recordMediaByNodeId: [
				121,
				{
					nodeId: [2, 'ID!'],
				},
			],
			upvoteByNodeId: [
				90,
				{
					nodeId: [2, 'ID!'],
				},
			],
			userByNodeId: [
				21,
				{
					nodeId: [2, 'ID!'],
				},
			],
			userPointByNodeId: [
				135,
				{
					nodeId: [2, 'ID!'],
				},
			],
			versionByNodeId: [
				247,
				{
					nodeId: [2, 'ID!'],
				},
			],
			voteByNodeId: [
				100,
				{
					nodeId: [2, 'ID!'],
				},
			],
			worldRecordGlobalByNodeId: [
				95,
				{
					nodeId: [2, 'ID!'],
				},
			],
			__typename: [7],
		},
	},
};
