export default {
	scalars: [
		2, 5, 6, 7, 9, 11, 12, 13, 22, 23, 35, 48, 70, 75, 80, 82, 86, 91, 96, 101,
		106, 112, 117, 122, 127, 132,
	],
	types: {
		Query: {
			query: [0],
			nodeId: [2],
			node: [
				1,
				{
					nodeId: [2, 'ID!'],
				},
			],
			allVersionInfos: [
				3,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [13, '[VersionInfosOrderBy!]'],
					condition: [14],
					filter: [15],
				},
			],
			allFavorites: [
				19,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [23, '[FavoritesOrderBy!]'],
					condition: [24],
					filter: [25],
				},
			],
			allLevels: [
				115,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [117, '[LevelsOrderBy!]'],
					condition: [118],
					filter: [41],
				},
			],
			allLevelItems: [
				67,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [70, '[LevelItemsOrderBy!]'],
					condition: [71],
					filter: [44],
				},
			],
			allLevelMetadata: [
				72,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [75, '[LevelMetadataOrderBy!]'],
					condition: [76],
					filter: [46],
				},
			],
			allLevelPoints: [
				77,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [80, '[LevelPointsOrderBy!]'],
					condition: [81],
					filter: [50],
				},
			],
			allLevelRequests: [
				119,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [122, '[LevelRequestsOrderBy!]'],
					condition: [123],
					filter: [124],
				},
			],
			allPersonalBestGlobals: [
				63,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [82, '[PersonalBestGlobalsOrderBy!]'],
					condition: [83],
					filter: [32],
				},
			],
			allRecords: [
				84,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [86, '[RecordsOrderBy!]'],
					condition: [87],
					filter: [33],
				},
			],
			allRecordMedias: [
				104,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [106, '[RecordMediasOrderBy!]'],
					condition: [107],
					filter: [37],
				},
			],
			allUpvotes: [
				88,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [91, '[UpvotesOrderBy!]'],
					condition: [92],
					filter: [54],
				},
			],
			allUsers: [
				125,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [127, '[UsersOrderBy!]'],
					condition: [128],
					filter: [27],
				},
			],
			allUserPoints: [
				109,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [112, '[UserPointsOrderBy!]'],
					condition: [113],
					filter: [59],
				},
			],
			allVersions: [
				129,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [132, '[VersionsOrderBy!]'],
					condition: [133],
					filter: [134],
				},
			],
			allVotes: [
				98,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [101, '[VotesOrderBy!]'],
					condition: [102],
					filter: [57],
				},
			],
			allWorldRecordGlobals: [
				93,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [96, '[WorldRecordGlobalsOrderBy!]'],
					condition: [97],
					filter: [40],
				},
			],
			favoriteById: [
				20,
				{
					id: [12, 'Int!'],
				},
			],
			levelById: [
				66,
				{
					id: [12, 'Int!'],
				},
			],
			levelByHash: [
				66,
				{
					hash: [7, 'String!'],
				},
			],
			levelItemById: [
				68,
				{
					id: [12, 'Int!'],
				},
			],
			levelMetadatumById: [
				73,
				{
					id: [12, 'Int!'],
				},
			],
			levelPointById: [
				78,
				{
					id: [12, 'Int!'],
				},
			],
			levelRequestById: [
				120,
				{
					id: [12, 'Int!'],
				},
			],
			personalBestGlobalById: [
				64,
				{
					id: [12, 'Int!'],
				},
			],
			recordById: [
				65,
				{
					id: [12, 'Int!'],
				},
			],
			recordMediaById: [
				103,
				{
					id: [12, 'Int!'],
				},
			],
			recordMediaByIdRecord: [
				103,
				{
					idRecord: [12, 'Int!'],
				},
			],
			upvoteById: [
				89,
				{
					id: [12, 'Int!'],
				},
			],
			userById: [
				21,
				{
					id: [12, 'Int!'],
				},
			],
			userPointById: [
				110,
				{
					id: [12, 'Int!'],
				},
			],
			versionById: [
				130,
				{
					id: [12, 'Int!'],
				},
			],
			voteById: [
				99,
				{
					id: [12, 'Int!'],
				},
			],
			worldRecordGlobalById: [
				94,
				{
					id: [12, 'Int!'],
				},
			],
			zRtm: [
				135,
				{
					pMinAuthorTime: [35],
					pMaxAuthorTime: [35],
					pMinRecords: [12],
					pMaxRecords: [12],
					pExcludedAuthorIds: [12, '[Int]'],
					pExcludedHashes: [7, '[String]'],
					pMinCheckpoints: [12],
					pMaxCheckpoints: [12],
					pMinFinishes: [12],
					pMaxFinishes: [12],
					pMinBlocks: [12],
					pMaxBlocks: [12],
					pSampleSize: [12],
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					filter: [138],
				},
			],
			favorite: [
				20,
				{
					nodeId: [2, 'ID!'],
				},
			],
			level: [
				66,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelItem: [
				68,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelMetadatum: [
				73,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelPoint: [
				78,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelRequest: [
				120,
				{
					nodeId: [2, 'ID!'],
				},
			],
			personalBestGlobal: [
				64,
				{
					nodeId: [2, 'ID!'],
				},
			],
			record: [
				65,
				{
					nodeId: [2, 'ID!'],
				},
			],
			recordMedia: [
				103,
				{
					nodeId: [2, 'ID!'],
				},
			],
			upvote: [
				89,
				{
					nodeId: [2, 'ID!'],
				},
			],
			user: [
				21,
				{
					nodeId: [2, 'ID!'],
				},
			],
			userPoint: [
				110,
				{
					nodeId: [2, 'ID!'],
				},
			],
			version: [
				130,
				{
					nodeId: [2, 'ID!'],
				},
			],
			vote: [
				99,
				{
					nodeId: [2, 'ID!'],
				},
			],
			worldRecordGlobal: [
				94,
				{
					nodeId: [2, 'ID!'],
				},
			],
			__typename: [7],
		},
		Node: {
			nodeId: [2],
			on_Query: [0],
			on_Favorite: [20],
			on_User: [21],
			on_PersonalBestGlobal: [64],
			on_Record: [65],
			on_Level: [66],
			on_LevelItem: [68],
			on_LevelMetadatum: [73],
			on_LevelPoint: [78],
			on_Upvote: [89],
			on_WorldRecordGlobal: [94],
			on_Vote: [99],
			on_RecordMedia: [103],
			on_UserPoint: [110],
			on_LevelRequest: [120],
			on_Version: [130],
			__typename: [7],
		},
		ID: {},
		VersionInfosConnection: {
			nodes: [4],
			edges: [8],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		VersionInfo: {
			version: [5],
			appliedOn: [6],
			description: [7],
			__typename: [7],
		},
		BigInt: {},
		Datetime: {},
		String: {},
		VersionInfosEdge: {
			cursor: [9],
			node: [4],
			__typename: [7],
		},
		Cursor: {},
		PageInfo: {
			hasNextPage: [11],
			hasPreviousPage: [11],
			startCursor: [9],
			endCursor: [9],
			__typename: [7],
		},
		Boolean: {},
		Int: {},
		VersionInfosOrderBy: {},
		VersionInfoCondition: {
			version: [5],
			appliedOn: [6],
			description: [7],
			__typename: [7],
		},
		VersionInfoFilter: {
			version: [16],
			appliedOn: [17],
			description: [18],
			and: [15],
			or: [15],
			not: [15],
			__typename: [7],
		},
		BigIntFilter: {
			isNull: [11],
			equalTo: [5],
			notEqualTo: [5],
			distinctFrom: [5],
			notDistinctFrom: [5],
			in: [5],
			notIn: [5],
			lessThan: [5],
			lessThanOrEqualTo: [5],
			greaterThan: [5],
			greaterThanOrEqualTo: [5],
			__typename: [7],
		},
		DatetimeFilter: {
			isNull: [11],
			equalTo: [6],
			notEqualTo: [6],
			distinctFrom: [6],
			notDistinctFrom: [6],
			in: [6],
			notIn: [6],
			lessThan: [6],
			lessThanOrEqualTo: [6],
			greaterThan: [6],
			greaterThanOrEqualTo: [6],
			__typename: [7],
		},
		StringFilter: {
			isNull: [11],
			equalTo: [7],
			notEqualTo: [7],
			distinctFrom: [7],
			notDistinctFrom: [7],
			in: [7],
			notIn: [7],
			lessThan: [7],
			lessThanOrEqualTo: [7],
			greaterThan: [7],
			greaterThanOrEqualTo: [7],
			includes: [7],
			notIncludes: [7],
			includesInsensitive: [7],
			notIncludesInsensitive: [7],
			startsWith: [7],
			notStartsWith: [7],
			startsWithInsensitive: [7],
			notStartsWithInsensitive: [7],
			endsWith: [7],
			notEndsWith: [7],
			endsWithInsensitive: [7],
			notEndsWithInsensitive: [7],
			like: [7],
			notLike: [7],
			likeInsensitive: [7],
			notLikeInsensitive: [7],
			equalToInsensitive: [7],
			notEqualToInsensitive: [7],
			distinctFromInsensitive: [7],
			notDistinctFromInsensitive: [7],
			inInsensitive: [7],
			notInInsensitive: [7],
			lessThanInsensitive: [7],
			lessThanOrEqualToInsensitive: [7],
			greaterThanInsensitive: [7],
			greaterThanOrEqualToInsensitive: [7],
			__typename: [7],
		},
		FavoritesConnection: {
			nodes: [20],
			edges: [114],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		Favorite: {
			nodeId: [2],
			id: [12],
			idUser: [12],
			dateCreated: [6],
			dateUpdated: [6],
			idLevel: [12],
			userByIdUser: [21],
			levelByIdLevel: [66],
			__typename: [7],
		},
		User: {
			nodeId: [2],
			id: [12],
			steamName: [7],
			banned: [11],
			dateCreated: [6],
			dateUpdated: [6],
			steamId: [22],
			discordId: [22],
			favoritesByIdUser: [
				19,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [23, '[FavoritesOrderBy!]'],
					condition: [24],
					filter: [25],
				},
			],
			personalBestGlobalsByIdUser: [
				63,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [82, '[PersonalBestGlobalsOrderBy!]'],
					condition: [83],
					filter: [32],
				},
			],
			userPointsByIdUser: [
				109,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [112, '[UserPointsOrderBy!]'],
					condition: [113],
					filter: [59],
				},
			],
			recordsByIdUser: [
				84,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [86, '[RecordsOrderBy!]'],
					condition: [87],
					filter: [33],
				},
			],
			upvotesByIdUser: [
				88,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [91, '[UpvotesOrderBy!]'],
					condition: [92],
					filter: [54],
				},
			],
			votesByIdUser: [
				98,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [101, '[VotesOrderBy!]'],
					condition: [102],
					filter: [57],
				},
			],
			__typename: [7],
		},
		BigFloat: {},
		FavoritesOrderBy: {},
		FavoriteCondition: {
			id: [12],
			idUser: [12],
			dateCreated: [6],
			dateUpdated: [6],
			idLevel: [12],
			__typename: [7],
		},
		FavoriteFilter: {
			id: [26],
			idUser: [26],
			dateCreated: [17],
			dateUpdated: [17],
			idLevel: [26],
			userByIdUser: [27],
			levelByIdLevel: [41],
			and: [25],
			or: [25],
			not: [25],
			__typename: [7],
		},
		IntFilter: {
			isNull: [11],
			equalTo: [12],
			notEqualTo: [12],
			distinctFrom: [12],
			notDistinctFrom: [12],
			in: [12],
			notIn: [12],
			lessThan: [12],
			lessThanOrEqualTo: [12],
			greaterThan: [12],
			greaterThanOrEqualTo: [12],
			__typename: [7],
		},
		UserFilter: {
			id: [26],
			steamName: [18],
			banned: [28],
			dateCreated: [17],
			dateUpdated: [17],
			steamId: [29],
			discordId: [29],
			favoritesByIdUserList: [30],
			favoritesByIdUserListExist: [11],
			personalBestGlobalsByIdUserList: [31],
			personalBestGlobalsByIdUserListExist: [11],
			userPointsByIdUserList: [58],
			userPointsByIdUserListExist: [11],
			recordsByIdUserList: [60],
			recordsByIdUserListExist: [11],
			upvotesByIdUserList: [61],
			upvotesByIdUserListExist: [11],
			votesByIdUserList: [62],
			votesByIdUserListExist: [11],
			and: [27],
			or: [27],
			not: [27],
			__typename: [7],
		},
		BooleanFilter: {
			isNull: [11],
			equalTo: [11],
			notEqualTo: [11],
			distinctFrom: [11],
			notDistinctFrom: [11],
			in: [11],
			notIn: [11],
			lessThan: [11],
			lessThanOrEqualTo: [11],
			greaterThan: [11],
			greaterThanOrEqualTo: [11],
			__typename: [7],
		},
		BigFloatFilter: {
			isNull: [11],
			equalTo: [22],
			notEqualTo: [22],
			distinctFrom: [22],
			notDistinctFrom: [22],
			in: [22],
			notIn: [22],
			lessThan: [22],
			lessThanOrEqualTo: [22],
			greaterThan: [22],
			greaterThanOrEqualTo: [22],
			__typename: [7],
		},
		UserToManyFavoriteFilter: {
			every: [25],
			some: [25],
			none: [25],
			__typename: [7],
		},
		UserToManyPersonalBestGlobalFilter: {
			every: [32],
			some: [32],
			none: [32],
			__typename: [7],
		},
		PersonalBestGlobalFilter: {
			id: [26],
			idRecord: [26],
			idUser: [26],
			idLevel: [26],
			dateCreated: [17],
			dateUpdated: [17],
			recordByIdRecord: [33],
			userByIdUser: [27],
			levelByIdLevel: [41],
			and: [32],
			or: [32],
			not: [32],
			__typename: [7],
		},
		RecordFilter: {
			id: [26],
			idUser: [26],
			time: [34],
			gameVersion: [18],
			idLevel: [26],
			modVersion: [18],
			dateCreated: [17],
			dateUpdated: [17],
			splits: [36],
			speeds: [36],
			recordMediaByIdRecord: [37],
			recordMediaByIdRecordExists: [11],
			personalBestGlobalsByIdRecordList: [38],
			personalBestGlobalsByIdRecordListExist: [11],
			worldRecordGlobalsByIdRecordList: [39],
			worldRecordGlobalsByIdRecordListExist: [11],
			userByIdUser: [27],
			levelByIdLevel: [41],
			and: [33],
			or: [33],
			not: [33],
			__typename: [7],
		},
		FloatFilter: {
			isNull: [11],
			equalTo: [35],
			notEqualTo: [35],
			distinctFrom: [35],
			notDistinctFrom: [35],
			in: [35],
			notIn: [35],
			lessThan: [35],
			lessThanOrEqualTo: [35],
			greaterThan: [35],
			greaterThanOrEqualTo: [35],
			__typename: [7],
		},
		Float: {},
		FloatListFilter: {
			isNull: [11],
			equalTo: [35],
			notEqualTo: [35],
			distinctFrom: [35],
			notDistinctFrom: [35],
			lessThan: [35],
			lessThanOrEqualTo: [35],
			greaterThan: [35],
			greaterThanOrEqualTo: [35],
			contains: [35],
			containedBy: [35],
			overlaps: [35],
			anyEqualTo: [35],
			anyNotEqualTo: [35],
			anyLessThan: [35],
			anyLessThanOrEqualTo: [35],
			anyGreaterThan: [35],
			anyGreaterThanOrEqualTo: [35],
			__typename: [7],
		},
		RecordMediaFilter: {
			id: [26],
			idRecord: [26],
			ghostUrl: [18],
			dateCreated: [17],
			dateUpdated: [17],
			recordByIdRecord: [33],
			and: [37],
			or: [37],
			not: [37],
			__typename: [7],
		},
		RecordToManyPersonalBestGlobalFilter: {
			every: [32],
			some: [32],
			none: [32],
			__typename: [7],
		},
		RecordToManyWorldRecordGlobalFilter: {
			every: [40],
			some: [40],
			none: [40],
			__typename: [7],
		},
		WorldRecordGlobalFilter: {
			id: [26],
			idRecord: [26],
			idLevel: [26],
			dateCreated: [17],
			dateUpdated: [17],
			recordByIdRecord: [33],
			levelByIdLevel: [41],
			and: [40],
			or: [40],
			not: [40],
			__typename: [7],
		},
		LevelFilter: {
			id: [26],
			hash: [18],
			dateCreated: [17],
			dateUpdated: [17],
			favoritesByIdLevelList: [42],
			favoritesByIdLevelListExist: [11],
			levelItemsByIdLevelList: [43],
			levelItemsByIdLevelListExist: [11],
			levelMetadataByIdLevelList: [45],
			levelMetadataByIdLevelListExist: [11],
			levelPointsByIdLevelList: [49],
			levelPointsByIdLevelListExist: [11],
			personalBestGlobalsByIdLevelList: [51],
			personalBestGlobalsByIdLevelListExist: [11],
			recordsByIdLevelList: [52],
			recordsByIdLevelListExist: [11],
			upvotesByIdLevelList: [53],
			upvotesByIdLevelListExist: [11],
			worldRecordGlobalsByIdLevelList: [55],
			worldRecordGlobalsByIdLevelListExist: [11],
			votesByIdLevelList: [56],
			votesByIdLevelListExist: [11],
			and: [41],
			or: [41],
			not: [41],
			__typename: [7],
		},
		LevelToManyFavoriteFilter: {
			every: [25],
			some: [25],
			none: [25],
			__typename: [7],
		},
		LevelToManyLevelItemFilter: {
			every: [44],
			some: [44],
			none: [44],
			__typename: [7],
		},
		LevelItemFilter: {
			id: [26],
			idLevel: [26],
			workshopId: [29],
			authorId: [29],
			name: [18],
			imageUrl: [18],
			fileAuthor: [18],
			fileUid: [18],
			validationTimeAuthor: [34],
			validationTimeGold: [34],
			validationTimeSilver: [34],
			validationTimeBronze: [34],
			deleted: [28],
			createdAt: [17],
			updatedAt: [17],
			dateCreated: [17],
			dateUpdated: [17],
			levelByIdLevel: [41],
			and: [44],
			or: [44],
			not: [44],
			__typename: [7],
		},
		LevelToManyLevelMetadatumFilter: {
			every: [46],
			some: [46],
			none: [46],
			__typename: [7],
		},
		LevelMetadatumFilter: {
			id: [26],
			idLevel: [26],
			amountCheckpoints: [26],
			amountFinishes: [26],
			amountBlocks: [26],
			typeGround: [26],
			typeSkybox: [26],
			blocks: [47],
			dateCreated: [17],
			dateUpdated: [17],
			levelByIdLevel: [41],
			and: [46],
			or: [46],
			not: [46],
			__typename: [7],
		},
		JSONFilter: {
			isNull: [11],
			equalTo: [48],
			notEqualTo: [48],
			distinctFrom: [48],
			notDistinctFrom: [48],
			in: [48],
			notIn: [48],
			lessThan: [48],
			lessThanOrEqualTo: [48],
			greaterThan: [48],
			greaterThanOrEqualTo: [48],
			contains: [48],
			containsKey: [7],
			containsAllKeys: [7],
			containsAnyKeys: [7],
			containedBy: [48],
			__typename: [7],
		},
		JSON: {},
		LevelToManyLevelPointFilter: {
			every: [50],
			some: [50],
			none: [50],
			__typename: [7],
		},
		LevelPointFilter: {
			id: [26],
			points: [26],
			idLevel: [26],
			dateCreated: [17],
			dateUpdated: [17],
			levelByIdLevel: [41],
			and: [50],
			or: [50],
			not: [50],
			__typename: [7],
		},
		LevelToManyPersonalBestGlobalFilter: {
			every: [32],
			some: [32],
			none: [32],
			__typename: [7],
		},
		LevelToManyRecordFilter: {
			every: [33],
			some: [33],
			none: [33],
			__typename: [7],
		},
		LevelToManyUpvoteFilter: {
			every: [54],
			some: [54],
			none: [54],
			__typename: [7],
		},
		UpvoteFilter: {
			id: [26],
			idUser: [26],
			idLevel: [26],
			dateCreated: [17],
			dateUpdated: [17],
			userByIdUser: [27],
			levelByIdLevel: [41],
			and: [54],
			or: [54],
			not: [54],
			__typename: [7],
		},
		LevelToManyWorldRecordGlobalFilter: {
			every: [40],
			some: [40],
			none: [40],
			__typename: [7],
		},
		LevelToManyVoteFilter: {
			every: [57],
			some: [57],
			none: [57],
			__typename: [7],
		},
		VoteFilter: {
			id: [26],
			idUser: [26],
			idLevel: [26],
			value: [26],
			dateCreated: [17],
			dateUpdated: [17],
			userByIdUser: [27],
			levelByIdLevel: [41],
			and: [57],
			or: [57],
			not: [57],
			__typename: [7],
		},
		UserToManyUserPointFilter: {
			every: [59],
			some: [59],
			none: [59],
			__typename: [7],
		},
		UserPointFilter: {
			id: [26],
			idUser: [26],
			points: [26],
			dateCreated: [17],
			dateUpdated: [17],
			rank: [26],
			worldRecords: [26],
			totalPoints: [26],
			userByIdUser: [27],
			and: [59],
			or: [59],
			not: [59],
			__typename: [7],
		},
		UserToManyRecordFilter: {
			every: [33],
			some: [33],
			none: [33],
			__typename: [7],
		},
		UserToManyUpvoteFilter: {
			every: [54],
			some: [54],
			none: [54],
			__typename: [7],
		},
		UserToManyVoteFilter: {
			every: [57],
			some: [57],
			none: [57],
			__typename: [7],
		},
		PersonalBestGlobalsConnection: {
			nodes: [64],
			edges: [108],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		PersonalBestGlobal: {
			nodeId: [2],
			id: [12],
			idRecord: [12],
			idUser: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			recordByIdRecord: [65],
			userByIdUser: [21],
			levelByIdLevel: [66],
			__typename: [7],
		},
		Record: {
			nodeId: [2],
			id: [12],
			idUser: [12],
			time: [35],
			gameVersion: [7],
			idLevel: [12],
			modVersion: [7],
			dateCreated: [6],
			dateUpdated: [6],
			splits: [35],
			speeds: [35],
			userByIdUser: [21],
			levelByIdLevel: [66],
			recordMediaByIdRecord: [103],
			recordMediasByIdRecord: [
				104,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [106, '[RecordMediasOrderBy!]'],
					condition: [107],
					filter: [37],
				},
			],
			personalBestGlobalsByIdRecord: [
				63,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [82, '[PersonalBestGlobalsOrderBy!]'],
					condition: [83],
					filter: [32],
				},
			],
			worldRecordGlobalsByIdRecord: [
				93,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [96, '[WorldRecordGlobalsOrderBy!]'],
					condition: [97],
					filter: [40],
				},
			],
			__typename: [7],
		},
		Level: {
			nodeId: [2],
			id: [12],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			favoritesByIdLevel: [
				19,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [23, '[FavoritesOrderBy!]'],
					condition: [24],
					filter: [25],
				},
			],
			levelItemsByIdLevel: [
				67,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [70, '[LevelItemsOrderBy!]'],
					condition: [71],
					filter: [44],
				},
			],
			levelMetadataByIdLevel: [
				72,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [75, '[LevelMetadataOrderBy!]'],
					condition: [76],
					filter: [46],
				},
			],
			levelPointsByIdLevel: [
				77,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [80, '[LevelPointsOrderBy!]'],
					condition: [81],
					filter: [50],
				},
			],
			personalBestGlobalsByIdLevel: [
				63,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [82, '[PersonalBestGlobalsOrderBy!]'],
					condition: [83],
					filter: [32],
				},
			],
			recordsByIdLevel: [
				84,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [86, '[RecordsOrderBy!]'],
					condition: [87],
					filter: [33],
				},
			],
			upvotesByIdLevel: [
				88,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [91, '[UpvotesOrderBy!]'],
					condition: [92],
					filter: [54],
				},
			],
			worldRecordGlobalsByIdLevel: [
				93,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [96, '[WorldRecordGlobalsOrderBy!]'],
					condition: [97],
					filter: [40],
				},
			],
			votesByIdLevel: [
				98,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [101, '[VotesOrderBy!]'],
					condition: [102],
					filter: [57],
				},
			],
			__typename: [7],
		},
		LevelItemsConnection: {
			nodes: [68],
			edges: [69],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelItem: {
			nodeId: [2],
			id: [12],
			idLevel: [12],
			workshopId: [22],
			authorId: [22],
			name: [7],
			imageUrl: [7],
			fileAuthor: [7],
			fileUid: [7],
			validationTimeAuthor: [35],
			validationTimeGold: [35],
			validationTimeSilver: [35],
			validationTimeBronze: [35],
			deleted: [11],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			levelByIdLevel: [66],
			__typename: [7],
		},
		LevelItemsEdge: {
			cursor: [9],
			node: [68],
			__typename: [7],
		},
		LevelItemsOrderBy: {},
		LevelItemCondition: {
			id: [12],
			idLevel: [12],
			workshopId: [22],
			authorId: [22],
			name: [7],
			imageUrl: [7],
			fileAuthor: [7],
			fileUid: [7],
			validationTimeAuthor: [35],
			validationTimeGold: [35],
			validationTimeSilver: [35],
			validationTimeBronze: [35],
			deleted: [11],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelMetadataConnection: {
			nodes: [73],
			edges: [74],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelMetadatum: {
			nodeId: [2],
			id: [12],
			idLevel: [12],
			amountCheckpoints: [12],
			amountFinishes: [12],
			amountBlocks: [12],
			typeGround: [12],
			typeSkybox: [12],
			blocks: [48],
			dateCreated: [6],
			dateUpdated: [6],
			levelByIdLevel: [66],
			__typename: [7],
		},
		LevelMetadataEdge: {
			cursor: [9],
			node: [73],
			__typename: [7],
		},
		LevelMetadataOrderBy: {},
		LevelMetadatumCondition: {
			id: [12],
			idLevel: [12],
			amountCheckpoints: [12],
			amountFinishes: [12],
			amountBlocks: [12],
			typeGround: [12],
			typeSkybox: [12],
			blocks: [48],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelPointsConnection: {
			nodes: [78],
			edges: [79],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelPoint: {
			nodeId: [2],
			id: [12],
			points: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			levelByIdLevel: [66],
			__typename: [7],
		},
		LevelPointsEdge: {
			cursor: [9],
			node: [78],
			__typename: [7],
		},
		LevelPointsOrderBy: {},
		LevelPointCondition: {
			id: [12],
			points: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		PersonalBestGlobalsOrderBy: {},
		PersonalBestGlobalCondition: {
			id: [12],
			idRecord: [12],
			idUser: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		RecordsConnection: {
			nodes: [65],
			edges: [85],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		RecordsEdge: {
			cursor: [9],
			node: [65],
			__typename: [7],
		},
		RecordsOrderBy: {},
		RecordCondition: {
			id: [12],
			idUser: [12],
			time: [35],
			gameVersion: [7],
			idLevel: [12],
			modVersion: [7],
			dateCreated: [6],
			dateUpdated: [6],
			splits: [35],
			speeds: [35],
			__typename: [7],
		},
		UpvotesConnection: {
			nodes: [89],
			edges: [90],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		Upvote: {
			nodeId: [2],
			id: [12],
			idUser: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			userByIdUser: [21],
			levelByIdLevel: [66],
			__typename: [7],
		},
		UpvotesEdge: {
			cursor: [9],
			node: [89],
			__typename: [7],
		},
		UpvotesOrderBy: {},
		UpvoteCondition: {
			id: [12],
			idUser: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		WorldRecordGlobalsConnection: {
			nodes: [94],
			edges: [95],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		WorldRecordGlobal: {
			nodeId: [2],
			id: [12],
			idRecord: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			recordByIdRecord: [65],
			levelByIdLevel: [66],
			__typename: [7],
		},
		WorldRecordGlobalsEdge: {
			cursor: [9],
			node: [94],
			__typename: [7],
		},
		WorldRecordGlobalsOrderBy: {},
		WorldRecordGlobalCondition: {
			id: [12],
			idRecord: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		VotesConnection: {
			nodes: [99],
			edges: [100],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		Vote: {
			nodeId: [2],
			id: [12],
			idUser: [12],
			idLevel: [12],
			value: [12],
			dateCreated: [6],
			dateUpdated: [6],
			userByIdUser: [21],
			levelByIdLevel: [66],
			__typename: [7],
		},
		VotesEdge: {
			cursor: [9],
			node: [99],
			__typename: [7],
		},
		VotesOrderBy: {},
		VoteCondition: {
			id: [12],
			idUser: [12],
			idLevel: [12],
			value: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		RecordMedia: {
			nodeId: [2],
			id: [12],
			idRecord: [12],
			ghostUrl: [7],
			dateCreated: [6],
			dateUpdated: [6],
			recordByIdRecord: [65],
			__typename: [7],
		},
		RecordMediasConnection: {
			nodes: [103],
			edges: [105],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		RecordMediasEdge: {
			cursor: [9],
			node: [103],
			__typename: [7],
		},
		RecordMediasOrderBy: {},
		RecordMediaCondition: {
			id: [12],
			idRecord: [12],
			ghostUrl: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		PersonalBestGlobalsEdge: {
			cursor: [9],
			node: [64],
			__typename: [7],
		},
		UserPointsConnection: {
			nodes: [110],
			edges: [111],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		UserPoint: {
			nodeId: [2],
			id: [12],
			idUser: [12],
			points: [12],
			dateCreated: [6],
			dateUpdated: [6],
			rank: [12],
			worldRecords: [12],
			totalPoints: [12],
			userByIdUser: [21],
			__typename: [7],
		},
		UserPointsEdge: {
			cursor: [9],
			node: [110],
			__typename: [7],
		},
		UserPointsOrderBy: {},
		UserPointCondition: {
			id: [12],
			idUser: [12],
			points: [12],
			dateCreated: [6],
			dateUpdated: [6],
			rank: [12],
			worldRecords: [12],
			totalPoints: [12],
			__typename: [7],
		},
		FavoritesEdge: {
			cursor: [9],
			node: [20],
			__typename: [7],
		},
		LevelsConnection: {
			nodes: [66],
			edges: [116],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelsEdge: {
			cursor: [9],
			node: [66],
			__typename: [7],
		},
		LevelsOrderBy: {},
		LevelCondition: {
			id: [12],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelRequestsConnection: {
			nodes: [120],
			edges: [121],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelRequest: {
			nodeId: [2],
			id: [12],
			workshopId: [22],
			uid: [7],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelRequestsEdge: {
			cursor: [9],
			node: [120],
			__typename: [7],
		},
		LevelRequestsOrderBy: {},
		LevelRequestCondition: {
			id: [12],
			workshopId: [22],
			uid: [7],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelRequestFilter: {
			id: [26],
			workshopId: [29],
			uid: [18],
			hash: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [124],
			or: [124],
			not: [124],
			__typename: [7],
		},
		UsersConnection: {
			nodes: [21],
			edges: [126],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		UsersEdge: {
			cursor: [9],
			node: [21],
			__typename: [7],
		},
		UsersOrderBy: {},
		UserCondition: {
			id: [12],
			steamName: [7],
			banned: [11],
			dateCreated: [6],
			dateUpdated: [6],
			steamId: [22],
			discordId: [22],
			__typename: [7],
		},
		VersionsConnection: {
			nodes: [130],
			edges: [131],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		Version: {
			nodeId: [2],
			id: [12],
			minimum: [7],
			latest: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		VersionsEdge: {
			cursor: [9],
			node: [130],
			__typename: [7],
		},
		VersionsOrderBy: {},
		VersionCondition: {
			id: [12],
			minimum: [7],
			latest: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		VersionFilter: {
			id: [26],
			minimum: [18],
			latest: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [134],
			or: [134],
			not: [134],
			__typename: [7],
		},
		ZRtmConnection: {
			nodes: [136],
			edges: [137],
			totalCount: [12],
			__typename: [7],
		},
		ZRtmRecord: {
			id: [12],
			idLevel: [12],
			workshopId: [22],
			authorId: [22],
			name: [7],
			imageUrl: [7],
			fileAuthor: [7],
			fileUid: [7],
			validationTimeAuthor: [35],
			validationTimeGold: [35],
			validationTimeSilver: [35],
			validationTimeBronze: [35],
			deleted: [11],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			amountCheckpoints: [12],
			amountFinishes: [12],
			amountBlocks: [12],
			numRecords: [5],
			__typename: [7],
		},
		ZRtmEdge: {
			cursor: [9],
			node: [136],
			__typename: [7],
		},
		ZRtmRecordFilter: {
			id: [26],
			idLevel: [26],
			workshopId: [29],
			authorId: [29],
			name: [18],
			imageUrl: [18],
			fileAuthor: [18],
			fileUid: [18],
			validationTimeAuthor: [34],
			validationTimeGold: [34],
			validationTimeSilver: [34],
			validationTimeBronze: [34],
			deleted: [28],
			createdAt: [17],
			updatedAt: [17],
			dateCreated: [17],
			dateUpdated: [17],
			amountCheckpoints: [26],
			amountFinishes: [26],
			amountBlocks: [26],
			numRecords: [16],
			and: [138],
			or: [138],
			not: [138],
			__typename: [7],
		},
		Mutation: {
			updateWorldRecordGlobal: [
				140,
				{
					input: [141, 'UpdateWorldRecordGlobalInput!'],
				},
			],
			__typename: [7],
		},
		UpdateWorldRecordGlobalPayload: {
			clientMutationId: [7],
			query: [0],
			__typename: [7],
		},
		UpdateWorldRecordGlobalInput: {
			clientMutationId: [7],
			__typename: [7],
		},
	},
};
