export default {
	scalars: [
		2, 5, 6, 8, 9, 10, 11, 12, 26, 37, 41, 66, 71, 76, 78, 82, 87, 92, 97, 101,
		118, 124, 134, 139, 161, 169,
	],
	types: {
		Query: {
			query: [0],
			nodeId: [2],
			node: [
				1,
				{
					nodeId: [2, 'ID!'],
				},
			],
			favourites: [
				3,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [12, '[FavouritesOrderBy!]'],
					condition: [13],
					filter: [14],
				},
			],
			levels: [
				156,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [124, '[LevelsOrderBy!]'],
					condition: [125],
					filter: [32],
				},
			],
			levelItems: [
				62,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [66, '[LevelItemsOrderBy!]'],
					condition: [67],
					filter: [35],
				},
			],
			levelMetadata: [
				68,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [71, '[LevelMetadataOrderBy!]'],
					condition: [72],
					filter: [39],
				},
			],
			levelPoints: [
				73,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [76, '[LevelPointsOrderBy!]'],
					condition: [77],
					filter: [43],
				},
			],
			levelPointsHistories: [
				94,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [97, '[LevelPointsHistoriesOrderBy!]'],
					condition: [98],
					filter: [50],
				},
			],
			levelRequests: [
				158,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [161, '[LevelRequestsOrderBy!]'],
					condition: [162],
					filter: [163],
				},
			],
			personalBestGlobals: [
				58,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [78, '[PersonalBestGlobalsOrderBy!]'],
					condition: [79],
					filter: [23],
				},
			],
			records: [
				80,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [82, '[RecordsOrderBy!]'],
					condition: [83],
					filter: [24],
				},
			],
			recordMedias: [
				116,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [118, '[RecordMediaOrderBy!]'],
					condition: [119],
					filter: [28],
				},
			],
			users: [
				164,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [101, '[UsersOrderBy!]'],
					condition: [102],
					filter: [17],
				},
			],
			userPoints: [
				131,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [134, '[UserPointsOrderBy!]'],
					condition: [135],
					filter: [52],
				},
			],
			userPointsHistories: [
				136,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [139, '[UserPointsHistoriesOrderBy!]'],
					condition: [140],
					filter: [57],
				},
			],
			versions: [
				166,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [169, '[VersionsOrderBy!]'],
					condition: [170],
					filter: [171],
				},
			],
			votes: [
				89,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [92, '[VotesOrderBy!]'],
					condition: [93],
					filter: [48],
				},
			],
			worldRecordGlobals: [
				84,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [87, '[WorldRecordGlobalsOrderBy!]'],
					condition: [88],
					filter: [31],
				},
			],
			favourite: [
				4,
				{
					id: [5, 'Int!'],
				},
			],
			level: [
				61,
				{
					id: [5, 'Int!'],
				},
			],
			levelByHash: [
				61,
				{
					hash: [8, 'String!'],
				},
			],
			levelItem: [
				63,
				{
					id: [5, 'Int!'],
				},
			],
			levelMetadatum: [
				69,
				{
					id: [5, 'Int!'],
				},
			],
			levelPoint: [
				74,
				{
					id: [5, 'Int!'],
				},
			],
			levelPointsHistory: [
				95,
				{
					id: [5, 'Int!'],
				},
			],
			levelRequest: [
				159,
				{
					id: [5, 'Int!'],
				},
			],
			personalBestGlobal: [
				59,
				{
					id: [5, 'Int!'],
				},
			],
			record: [
				60,
				{
					id: [5, 'Int!'],
				},
			],
			recordMedia: [
				115,
				{
					id: [5, 'Int!'],
				},
			],
			recordMediaByRecordId: [
				115,
				{
					recordId: [5, 'Int!'],
				},
			],
			user: [
				7,
				{
					id: [5, 'Int!'],
				},
			],
			userPoint: [
				132,
				{
					id: [5, 'Int!'],
				},
			],
			userPointsHistory: [
				137,
				{
					id: [5, 'Int!'],
				},
			],
			version: [
				167,
				{
					id: [5, 'Int!'],
				},
			],
			vote: [
				90,
				{
					id: [5, 'Int!'],
				},
			],
			worldRecordGlobal: [
				85,
				{
					id: [5, 'Int!'],
				},
			],
			zRtm: [
				172,
				{
					pMinAuthorTime: [26],
					pMaxAuthorTime: [26],
					pMinRecords: [5],
					pMaxRecords: [5],
					pExcludedAuthorIds: [5, '[Int]'],
					pExcludedHashes: [8, '[String]'],
					pMinCheckpoints: [5],
					pMaxCheckpoints: [5],
					pMinFinishes: [5],
					pMaxFinishes: [5],
					pMinBlocks: [5],
					pMaxBlocks: [5],
					pSampleSize: [5],
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					filter: [175],
				},
			],
			favouriteByNodeId: [
				4,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelByNodeId: [
				61,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelItemByNodeId: [
				63,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelMetadatumByNodeId: [
				69,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelPointByNodeId: [
				74,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelPointsHistoryByNodeId: [
				95,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelRequestByNodeId: [
				159,
				{
					nodeId: [2, 'ID!'],
				},
			],
			personalBestGlobalByNodeId: [
				59,
				{
					nodeId: [2, 'ID!'],
				},
			],
			recordByNodeId: [
				60,
				{
					nodeId: [2, 'ID!'],
				},
			],
			recordMediaByNodeId: [
				115,
				{
					nodeId: [2, 'ID!'],
				},
			],
			userByNodeId: [
				7,
				{
					nodeId: [2, 'ID!'],
				},
			],
			userPointByNodeId: [
				132,
				{
					nodeId: [2, 'ID!'],
				},
			],
			userPointsHistoryByNodeId: [
				137,
				{
					nodeId: [2, 'ID!'],
				},
			],
			versionByNodeId: [
				167,
				{
					nodeId: [2, 'ID!'],
				},
			],
			voteByNodeId: [
				90,
				{
					nodeId: [2, 'ID!'],
				},
			],
			worldRecordGlobalByNodeId: [
				85,
				{
					nodeId: [2, 'ID!'],
				},
			],
			__typename: [8],
		},
		Node: {
			nodeId: [2],
			on_Query: [0],
			on_Favourite: [4],
			on_User: [7],
			on_PersonalBestGlobal: [59],
			on_Record: [60],
			on_Level: [61],
			on_LevelItem: [63],
			on_LevelMetadatum: [69],
			on_LevelPoint: [74],
			on_WorldRecordGlobal: [85],
			on_Vote: [90],
			on_LevelPointsHistory: [95],
			on_RecordMedia: [115],
			on_UserPoint: [132],
			on_UserPointsHistory: [137],
			on_LevelRequest: [159],
			on_Version: [167],
			__typename: [8],
		},
		ID: {},
		FavouritesConnection: {
			nodes: [4],
			edges: [155],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		Favourite: {
			nodeId: [2],
			id: [5],
			userId: [5],
			dateCreated: [6],
			dateUpdated: [6],
			levelId: [5],
			user: [7],
			level: [61],
			__typename: [8],
		},
		Int: {},
		Datetime: {},
		User: {
			nodeId: [2],
			id: [5],
			steamName: [8],
			banned: [9],
			dateCreated: [6],
			dateUpdated: [6],
			steamId: [10],
			discordId: [10],
			favourites: [
				3,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [12, '[FavouritesOrderBy!]'],
					condition: [13],
					filter: [14],
				},
			],
			personalBestGlobals: [
				58,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [78, '[PersonalBestGlobalsOrderBy!]'],
					condition: [79],
					filter: [23],
				},
			],
			userPoints: [
				131,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [134, '[UserPointsOrderBy!]'],
					condition: [135],
					filter: [52],
				},
			],
			records: [
				80,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [82, '[RecordsOrderBy!]'],
					condition: [83],
					filter: [24],
				},
			],
			worldRecordGlobals: [
				84,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [87, '[WorldRecordGlobalsOrderBy!]'],
					condition: [88],
					filter: [31],
				},
			],
			votes: [
				89,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [92, '[VotesOrderBy!]'],
					condition: [93],
					filter: [48],
				},
			],
			userPointsHistories: [
				136,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [139, '[UserPointsHistoriesOrderBy!]'],
					condition: [140],
					filter: [57],
				},
			],
			levelsByFavourite: [
				141,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [124, '[LevelsOrderBy!]'],
					condition: [125],
					filter: [32],
				},
			],
			recordsByPersonalBestGlobal: [
				143,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [82, '[RecordsOrderBy!]'],
					condition: [83],
					filter: [24],
				},
			],
			levelsByPersonalBestGlobal: [
				145,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [124, '[LevelsOrderBy!]'],
					condition: [125],
					filter: [32],
				},
			],
			levelsByRecord: [
				147,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [124, '[LevelsOrderBy!]'],
					condition: [125],
					filter: [32],
				},
			],
			recordsByWorldRecordGlobal: [
				149,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [82, '[RecordsOrderBy!]'],
					condition: [83],
					filter: [24],
				},
			],
			levelsByWorldRecordGlobal: [
				151,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [124, '[LevelsOrderBy!]'],
					condition: [125],
					filter: [32],
				},
			],
			levelsByVote: [
				153,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [124, '[LevelsOrderBy!]'],
					condition: [125],
					filter: [32],
				},
			],
			__typename: [8],
		},
		String: {},
		Boolean: {},
		BigInt: {},
		Cursor: {},
		FavouritesOrderBy: {},
		FavouriteCondition: {
			id: [5],
			userId: [5],
			dateCreated: [6],
			dateUpdated: [6],
			levelId: [5],
			__typename: [8],
		},
		FavouriteFilter: {
			id: [15],
			userId: [15],
			dateCreated: [16],
			dateUpdated: [16],
			levelId: [15],
			user: [17],
			level: [32],
			and: [14],
			or: [14],
			not: [14],
			__typename: [8],
		},
		IntFilter: {
			isNull: [9],
			equalTo: [5],
			notEqualTo: [5],
			distinctFrom: [5],
			notDistinctFrom: [5],
			in: [5],
			notIn: [5],
			lessThan: [5],
			lessThanOrEqualTo: [5],
			greaterThan: [5],
			greaterThanOrEqualTo: [5],
			__typename: [8],
		},
		DatetimeFilter: {
			isNull: [9],
			equalTo: [6],
			notEqualTo: [6],
			distinctFrom: [6],
			notDistinctFrom: [6],
			in: [6],
			notIn: [6],
			lessThan: [6],
			lessThanOrEqualTo: [6],
			greaterThan: [6],
			greaterThanOrEqualTo: [6],
			__typename: [8],
		},
		UserFilter: {
			id: [15],
			steamName: [18],
			banned: [19],
			dateCreated: [16],
			dateUpdated: [16],
			steamId: [20],
			discordId: [20],
			favourites: [21],
			favouritesExist: [9],
			personalBestGlobals: [22],
			personalBestGlobalsExist: [9],
			userPoints: [51],
			userPointsExist: [9],
			records: [53],
			recordsExist: [9],
			worldRecordGlobals: [54],
			worldRecordGlobalsExist: [9],
			votes: [55],
			votesExist: [9],
			userPointsHistories: [56],
			userPointsHistoriesExist: [9],
			and: [17],
			or: [17],
			not: [17],
			__typename: [8],
		},
		StringFilter: {
			isNull: [9],
			equalTo: [8],
			notEqualTo: [8],
			distinctFrom: [8],
			notDistinctFrom: [8],
			in: [8],
			notIn: [8],
			lessThan: [8],
			lessThanOrEqualTo: [8],
			greaterThan: [8],
			greaterThanOrEqualTo: [8],
			includes: [8],
			notIncludes: [8],
			includesInsensitive: [8],
			notIncludesInsensitive: [8],
			startsWith: [8],
			notStartsWith: [8],
			startsWithInsensitive: [8],
			notStartsWithInsensitive: [8],
			endsWith: [8],
			notEndsWith: [8],
			endsWithInsensitive: [8],
			notEndsWithInsensitive: [8],
			like: [8],
			notLike: [8],
			likeInsensitive: [8],
			notLikeInsensitive: [8],
			equalToInsensitive: [8],
			notEqualToInsensitive: [8],
			distinctFromInsensitive: [8],
			notDistinctFromInsensitive: [8],
			inInsensitive: [8],
			notInInsensitive: [8],
			lessThanInsensitive: [8],
			lessThanOrEqualToInsensitive: [8],
			greaterThanInsensitive: [8],
			greaterThanOrEqualToInsensitive: [8],
			__typename: [8],
		},
		BooleanFilter: {
			isNull: [9],
			equalTo: [9],
			notEqualTo: [9],
			distinctFrom: [9],
			notDistinctFrom: [9],
			in: [9],
			notIn: [9],
			lessThan: [9],
			lessThanOrEqualTo: [9],
			greaterThan: [9],
			greaterThanOrEqualTo: [9],
			__typename: [8],
		},
		BigIntFilter: {
			isNull: [9],
			equalTo: [10],
			notEqualTo: [10],
			distinctFrom: [10],
			notDistinctFrom: [10],
			in: [10],
			notIn: [10],
			lessThan: [10],
			lessThanOrEqualTo: [10],
			greaterThan: [10],
			greaterThanOrEqualTo: [10],
			__typename: [8],
		},
		UserToManyFavouriteFilter: {
			every: [14],
			some: [14],
			none: [14],
			__typename: [8],
		},
		UserToManyPersonalBestGlobalFilter: {
			every: [23],
			some: [23],
			none: [23],
			__typename: [8],
		},
		PersonalBestGlobalFilter: {
			id: [15],
			recordId: [15],
			userId: [15],
			levelId: [15],
			dateCreated: [16],
			dateUpdated: [16],
			record: [24],
			user: [17],
			level: [32],
			and: [23],
			or: [23],
			not: [23],
			__typename: [8],
		},
		RecordFilter: {
			id: [15],
			userId: [15],
			time: [25],
			gameVersion: [18],
			levelId: [15],
			modVersion: [18],
			dateCreated: [16],
			dateUpdated: [16],
			splits: [27],
			speeds: [27],
			recordMedia: [28],
			recordMediaExists: [9],
			personalBestGlobals: [29],
			personalBestGlobalsExist: [9],
			worldRecordGlobals: [30],
			worldRecordGlobalsExist: [9],
			user: [17],
			level: [32],
			and: [24],
			or: [24],
			not: [24],
			__typename: [8],
		},
		FloatFilter: {
			isNull: [9],
			equalTo: [26],
			notEqualTo: [26],
			distinctFrom: [26],
			notDistinctFrom: [26],
			in: [26],
			notIn: [26],
			lessThan: [26],
			lessThanOrEqualTo: [26],
			greaterThan: [26],
			greaterThanOrEqualTo: [26],
			__typename: [8],
		},
		Float: {},
		FloatListFilter: {
			isNull: [9],
			equalTo: [26],
			notEqualTo: [26],
			distinctFrom: [26],
			notDistinctFrom: [26],
			lessThan: [26],
			lessThanOrEqualTo: [26],
			greaterThan: [26],
			greaterThanOrEqualTo: [26],
			contains: [26],
			containedBy: [26],
			overlaps: [26],
			anyEqualTo: [26],
			anyNotEqualTo: [26],
			anyLessThan: [26],
			anyLessThanOrEqualTo: [26],
			anyGreaterThan: [26],
			anyGreaterThanOrEqualTo: [26],
			__typename: [8],
		},
		RecordMediaFilter: {
			id: [15],
			recordId: [15],
			ghostUrl: [18],
			dateCreated: [16],
			dateUpdated: [16],
			record: [24],
			and: [28],
			or: [28],
			not: [28],
			__typename: [8],
		},
		RecordToManyPersonalBestGlobalFilter: {
			every: [23],
			some: [23],
			none: [23],
			__typename: [8],
		},
		RecordToManyWorldRecordGlobalFilter: {
			every: [31],
			some: [31],
			none: [31],
			__typename: [8],
		},
		WorldRecordGlobalFilter: {
			id: [15],
			recordId: [15],
			levelId: [15],
			dateCreated: [16],
			dateUpdated: [16],
			userId: [15],
			record: [24],
			level: [32],
			user: [17],
			and: [31],
			or: [31],
			not: [31],
			__typename: [8],
		},
		LevelFilter: {
			id: [15],
			hash: [18],
			dateCreated: [16],
			dateUpdated: [16],
			favourites: [33],
			favouritesExist: [9],
			levelItems: [34],
			levelItemsExist: [9],
			levelMetadata: [38],
			levelMetadataExist: [9],
			levelPoints: [42],
			levelPointsExist: [9],
			personalBestGlobals: [44],
			personalBestGlobalsExist: [9],
			records: [45],
			recordsExist: [9],
			worldRecordGlobals: [46],
			worldRecordGlobalsExist: [9],
			votes: [47],
			votesExist: [9],
			levelPointsHistories: [49],
			levelPointsHistoriesExist: [9],
			and: [32],
			or: [32],
			not: [32],
			__typename: [8],
		},
		LevelToManyFavouriteFilter: {
			every: [14],
			some: [14],
			none: [14],
			__typename: [8],
		},
		LevelToManyLevelItemFilter: {
			every: [35],
			some: [35],
			none: [35],
			__typename: [8],
		},
		LevelItemFilter: {
			id: [15],
			levelId: [15],
			workshopId: [36],
			authorId: [36],
			name: [18],
			imageUrl: [18],
			fileAuthor: [18],
			fileUid: [18],
			validationTimeAuthor: [25],
			validationTimeGold: [25],
			validationTimeSilver: [25],
			validationTimeBronze: [25],
			deleted: [19],
			createdAt: [16],
			updatedAt: [16],
			dateCreated: [16],
			dateUpdated: [16],
			level: [32],
			and: [35],
			or: [35],
			not: [35],
			__typename: [8],
		},
		BigFloatFilter: {
			isNull: [9],
			equalTo: [37],
			notEqualTo: [37],
			distinctFrom: [37],
			notDistinctFrom: [37],
			in: [37],
			notIn: [37],
			lessThan: [37],
			lessThanOrEqualTo: [37],
			greaterThan: [37],
			greaterThanOrEqualTo: [37],
			__typename: [8],
		},
		BigFloat: {},
		LevelToManyLevelMetadatumFilter: {
			every: [39],
			some: [39],
			none: [39],
			__typename: [8],
		},
		LevelMetadatumFilter: {
			id: [15],
			levelId: [15],
			amountCheckpoints: [15],
			amountFinishes: [15],
			amountBlocks: [15],
			typeGround: [15],
			typeSkybox: [15],
			blocks: [40],
			dateCreated: [16],
			dateUpdated: [16],
			level: [32],
			and: [39],
			or: [39],
			not: [39],
			__typename: [8],
		},
		JSONFilter: {
			isNull: [9],
			equalTo: [41],
			notEqualTo: [41],
			distinctFrom: [41],
			notDistinctFrom: [41],
			in: [41],
			notIn: [41],
			lessThan: [41],
			lessThanOrEqualTo: [41],
			greaterThan: [41],
			greaterThanOrEqualTo: [41],
			contains: [41],
			containsKey: [8],
			containsAllKeys: [8],
			containsAnyKeys: [8],
			containedBy: [41],
			__typename: [8],
		},
		JSON: {},
		LevelToManyLevelPointFilter: {
			every: [43],
			some: [43],
			none: [43],
			__typename: [8],
		},
		LevelPointFilter: {
			id: [15],
			points: [15],
			levelId: [15],
			dateCreated: [16],
			dateUpdated: [16],
			level: [32],
			and: [43],
			or: [43],
			not: [43],
			__typename: [8],
		},
		LevelToManyPersonalBestGlobalFilter: {
			every: [23],
			some: [23],
			none: [23],
			__typename: [8],
		},
		LevelToManyRecordFilter: {
			every: [24],
			some: [24],
			none: [24],
			__typename: [8],
		},
		LevelToManyWorldRecordGlobalFilter: {
			every: [31],
			some: [31],
			none: [31],
			__typename: [8],
		},
		LevelToManyVoteFilter: {
			every: [48],
			some: [48],
			none: [48],
			__typename: [8],
		},
		VoteFilter: {
			id: [15],
			userId: [15],
			levelId: [15],
			value: [15],
			dateCreated: [16],
			dateUpdated: [16],
			user: [17],
			level: [32],
			and: [48],
			or: [48],
			not: [48],
			__typename: [8],
		},
		LevelToManyLevelPointsHistoryFilter: {
			every: [50],
			some: [50],
			none: [50],
			__typename: [8],
		},
		LevelPointsHistoryFilter: {
			id: [15],
			levelId: [15],
			points: [15],
			dateCreated: [16],
			level: [32],
			and: [50],
			or: [50],
			not: [50],
			__typename: [8],
		},
		UserToManyUserPointFilter: {
			every: [52],
			some: [52],
			none: [52],
			__typename: [8],
		},
		UserPointFilter: {
			id: [15],
			userId: [15],
			points: [15],
			dateCreated: [16],
			dateUpdated: [16],
			rank: [15],
			worldRecords: [15],
			totalPoints: [15],
			user: [17],
			and: [52],
			or: [52],
			not: [52],
			__typename: [8],
		},
		UserToManyRecordFilter: {
			every: [24],
			some: [24],
			none: [24],
			__typename: [8],
		},
		UserToManyWorldRecordGlobalFilter: {
			every: [31],
			some: [31],
			none: [31],
			__typename: [8],
		},
		UserToManyVoteFilter: {
			every: [48],
			some: [48],
			none: [48],
			__typename: [8],
		},
		UserToManyUserPointsHistoryFilter: {
			every: [57],
			some: [57],
			none: [57],
			__typename: [8],
		},
		UserPointsHistoryFilter: {
			id: [15],
			userId: [15],
			points: [15],
			totalPoints: [15],
			rank: [15],
			worldRecords: [15],
			dateCreated: [16],
			user: [17],
			and: [57],
			or: [57],
			not: [57],
			__typename: [8],
		},
		PersonalBestGlobalsConnection: {
			nodes: [59],
			edges: [130],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		PersonalBestGlobal: {
			nodeId: [2],
			id: [5],
			recordId: [5],
			userId: [5],
			levelId: [5],
			dateCreated: [6],
			dateUpdated: [6],
			record: [60],
			user: [7],
			level: [61],
			__typename: [8],
		},
		Record: {
			nodeId: [2],
			id: [5],
			userId: [5],
			time: [26],
			gameVersion: [8],
			levelId: [5],
			modVersion: [8],
			dateCreated: [6],
			dateUpdated: [6],
			splits: [26],
			speeds: [26],
			user: [7],
			level: [61],
			recordMedia: [115],
			recordMedias: [
				116,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [118, '[RecordMediaOrderBy!]'],
					condition: [119],
					filter: [28],
				},
			],
			personalBestGlobals: [
				58,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [78, '[PersonalBestGlobalsOrderBy!]'],
					condition: [79],
					filter: [23],
				},
			],
			worldRecordGlobals: [
				84,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [87, '[WorldRecordGlobalsOrderBy!]'],
					condition: [88],
					filter: [31],
				},
			],
			usersByPersonalBestGlobal: [
				120,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [101, '[UsersOrderBy!]'],
					condition: [102],
					filter: [17],
				},
			],
			levelsByPersonalBestGlobal: [
				122,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [124, '[LevelsOrderBy!]'],
					condition: [125],
					filter: [32],
				},
			],
			levelsByWorldRecordGlobal: [
				126,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [124, '[LevelsOrderBy!]'],
					condition: [125],
					filter: [32],
				},
			],
			usersByWorldRecordGlobal: [
				128,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [101, '[UsersOrderBy!]'],
					condition: [102],
					filter: [17],
				},
			],
			__typename: [8],
		},
		Level: {
			nodeId: [2],
			id: [5],
			hash: [8],
			dateCreated: [6],
			dateUpdated: [6],
			favourites: [
				3,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [12, '[FavouritesOrderBy!]'],
					condition: [13],
					filter: [14],
				},
			],
			levelItems: [
				62,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [66, '[LevelItemsOrderBy!]'],
					condition: [67],
					filter: [35],
				},
			],
			levelMetadata: [
				68,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [71, '[LevelMetadataOrderBy!]'],
					condition: [72],
					filter: [39],
				},
			],
			levelPoints: [
				73,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [76, '[LevelPointsOrderBy!]'],
					condition: [77],
					filter: [43],
				},
			],
			personalBestGlobals: [
				58,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [78, '[PersonalBestGlobalsOrderBy!]'],
					condition: [79],
					filter: [23],
				},
			],
			records: [
				80,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [82, '[RecordsOrderBy!]'],
					condition: [83],
					filter: [24],
				},
			],
			worldRecordGlobals: [
				84,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [87, '[WorldRecordGlobalsOrderBy!]'],
					condition: [88],
					filter: [31],
				},
			],
			votes: [
				89,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [92, '[VotesOrderBy!]'],
					condition: [93],
					filter: [48],
				},
			],
			levelPointsHistories: [
				94,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [97, '[LevelPointsHistoriesOrderBy!]'],
					condition: [98],
					filter: [50],
				},
			],
			usersByFavourite: [
				99,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [101, '[UsersOrderBy!]'],
					condition: [102],
					filter: [17],
				},
			],
			recordsByPersonalBestGlobal: [
				103,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [82, '[RecordsOrderBy!]'],
					condition: [83],
					filter: [24],
				},
			],
			usersByPersonalBestGlobal: [
				105,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [101, '[UsersOrderBy!]'],
					condition: [102],
					filter: [17],
				},
			],
			usersByRecord: [
				107,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [101, '[UsersOrderBy!]'],
					condition: [102],
					filter: [17],
				},
			],
			recordsByWorldRecordGlobal: [
				109,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [82, '[RecordsOrderBy!]'],
					condition: [83],
					filter: [24],
				},
			],
			usersByWorldRecordGlobal: [
				111,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [101, '[UsersOrderBy!]'],
					condition: [102],
					filter: [17],
				},
			],
			usersByVote: [
				113,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [101, '[UsersOrderBy!]'],
					condition: [102],
					filter: [17],
				},
			],
			__typename: [8],
		},
		LevelItemsConnection: {
			nodes: [63],
			edges: [64],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		LevelItem: {
			nodeId: [2],
			id: [5],
			levelId: [5],
			workshopId: [37],
			authorId: [37],
			name: [8],
			imageUrl: [8],
			fileAuthor: [8],
			fileUid: [8],
			validationTimeAuthor: [26],
			validationTimeGold: [26],
			validationTimeSilver: [26],
			validationTimeBronze: [26],
			deleted: [9],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			level: [61],
			__typename: [8],
		},
		LevelItemsEdge: {
			cursor: [11],
			node: [63],
			__typename: [8],
		},
		PageInfo: {
			hasNextPage: [9],
			hasPreviousPage: [9],
			startCursor: [11],
			endCursor: [11],
			__typename: [8],
		},
		LevelItemsOrderBy: {},
		LevelItemCondition: {
			id: [5],
			levelId: [5],
			workshopId: [37],
			authorId: [37],
			name: [8],
			imageUrl: [8],
			fileAuthor: [8],
			fileUid: [8],
			validationTimeAuthor: [26],
			validationTimeGold: [26],
			validationTimeSilver: [26],
			validationTimeBronze: [26],
			deleted: [9],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [8],
		},
		LevelMetadataConnection: {
			nodes: [69],
			edges: [70],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		LevelMetadatum: {
			nodeId: [2],
			id: [5],
			levelId: [5],
			amountCheckpoints: [5],
			amountFinishes: [5],
			amountBlocks: [5],
			typeGround: [5],
			typeSkybox: [5],
			blocks: [41],
			dateCreated: [6],
			dateUpdated: [6],
			level: [61],
			__typename: [8],
		},
		LevelMetadataEdge: {
			cursor: [11],
			node: [69],
			__typename: [8],
		},
		LevelMetadataOrderBy: {},
		LevelMetadatumCondition: {
			id: [5],
			levelId: [5],
			amountCheckpoints: [5],
			amountFinishes: [5],
			amountBlocks: [5],
			typeGround: [5],
			typeSkybox: [5],
			blocks: [41],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [8],
		},
		LevelPointsConnection: {
			nodes: [74],
			edges: [75],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		LevelPoint: {
			nodeId: [2],
			id: [5],
			points: [5],
			levelId: [5],
			dateCreated: [6],
			dateUpdated: [6],
			level: [61],
			__typename: [8],
		},
		LevelPointsEdge: {
			cursor: [11],
			node: [74],
			__typename: [8],
		},
		LevelPointsOrderBy: {},
		LevelPointCondition: {
			id: [5],
			points: [5],
			levelId: [5],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [8],
		},
		PersonalBestGlobalsOrderBy: {},
		PersonalBestGlobalCondition: {
			id: [5],
			recordId: [5],
			userId: [5],
			levelId: [5],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [8],
		},
		RecordsConnection: {
			nodes: [60],
			edges: [81],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		RecordsEdge: {
			cursor: [11],
			node: [60],
			__typename: [8],
		},
		RecordsOrderBy: {},
		RecordCondition: {
			id: [5],
			userId: [5],
			time: [26],
			gameVersion: [8],
			levelId: [5],
			modVersion: [8],
			dateCreated: [6],
			dateUpdated: [6],
			splits: [26],
			speeds: [26],
			__typename: [8],
		},
		WorldRecordGlobalsConnection: {
			nodes: [85],
			edges: [86],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		WorldRecordGlobal: {
			nodeId: [2],
			id: [5],
			recordId: [5],
			levelId: [5],
			dateCreated: [6],
			dateUpdated: [6],
			userId: [5],
			record: [60],
			level: [61],
			user: [7],
			__typename: [8],
		},
		WorldRecordGlobalsEdge: {
			cursor: [11],
			node: [85],
			__typename: [8],
		},
		WorldRecordGlobalsOrderBy: {},
		WorldRecordGlobalCondition: {
			id: [5],
			recordId: [5],
			levelId: [5],
			dateCreated: [6],
			dateUpdated: [6],
			userId: [5],
			__typename: [8],
		},
		VotesConnection: {
			nodes: [90],
			edges: [91],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		Vote: {
			nodeId: [2],
			id: [5],
			userId: [5],
			levelId: [5],
			value: [5],
			dateCreated: [6],
			dateUpdated: [6],
			user: [7],
			level: [61],
			__typename: [8],
		},
		VotesEdge: {
			cursor: [11],
			node: [90],
			__typename: [8],
		},
		VotesOrderBy: {},
		VoteCondition: {
			id: [5],
			userId: [5],
			levelId: [5],
			value: [5],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [8],
		},
		LevelPointsHistoriesConnection: {
			nodes: [95],
			edges: [96],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		LevelPointsHistory: {
			nodeId: [2],
			id: [5],
			levelId: [5],
			points: [5],
			dateCreated: [6],
			level: [61],
			__typename: [8],
		},
		LevelPointsHistoriesEdge: {
			cursor: [11],
			node: [95],
			__typename: [8],
		},
		LevelPointsHistoriesOrderBy: {},
		LevelPointsHistoryCondition: {
			id: [5],
			levelId: [5],
			points: [5],
			dateCreated: [6],
			__typename: [8],
		},
		LevelUsersByFavouriteManyToManyConnection: {
			nodes: [7],
			edges: [100],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		LevelUsersByFavouriteManyToManyEdge: {
			cursor: [11],
			node: [7],
			favourites: [
				3,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [12, '[FavouritesOrderBy!]'],
					condition: [13],
					filter: [14],
				},
			],
			__typename: [8],
		},
		UsersOrderBy: {},
		UserCondition: {
			id: [5],
			steamName: [8],
			banned: [9],
			dateCreated: [6],
			dateUpdated: [6],
			steamId: [10],
			discordId: [10],
			__typename: [8],
		},
		LevelRecordsByPersonalBestGlobalManyToManyConnection: {
			nodes: [60],
			edges: [104],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		LevelRecordsByPersonalBestGlobalManyToManyEdge: {
			cursor: [11],
			node: [60],
			personalBestGlobals: [
				58,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [78, '[PersonalBestGlobalsOrderBy!]'],
					condition: [79],
					filter: [23],
				},
			],
			__typename: [8],
		},
		LevelUsersByPersonalBestGlobalManyToManyConnection: {
			nodes: [7],
			edges: [106],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		LevelUsersByPersonalBestGlobalManyToManyEdge: {
			cursor: [11],
			node: [7],
			personalBestGlobals: [
				58,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [78, '[PersonalBestGlobalsOrderBy!]'],
					condition: [79],
					filter: [23],
				},
			],
			__typename: [8],
		},
		LevelUsersByRecordManyToManyConnection: {
			nodes: [7],
			edges: [108],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		LevelUsersByRecordManyToManyEdge: {
			cursor: [11],
			node: [7],
			records: [
				80,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [82, '[RecordsOrderBy!]'],
					condition: [83],
					filter: [24],
				},
			],
			__typename: [8],
		},
		LevelRecordsByWorldRecordGlobalManyToManyConnection: {
			nodes: [60],
			edges: [110],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		LevelRecordsByWorldRecordGlobalManyToManyEdge: {
			cursor: [11],
			node: [60],
			worldRecordGlobals: [
				84,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [87, '[WorldRecordGlobalsOrderBy!]'],
					condition: [88],
					filter: [31],
				},
			],
			__typename: [8],
		},
		LevelUsersByWorldRecordGlobalManyToManyConnection: {
			nodes: [7],
			edges: [112],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		LevelUsersByWorldRecordGlobalManyToManyEdge: {
			cursor: [11],
			node: [7],
			worldRecordGlobals: [
				84,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [87, '[WorldRecordGlobalsOrderBy!]'],
					condition: [88],
					filter: [31],
				},
			],
			__typename: [8],
		},
		LevelUsersByVoteManyToManyConnection: {
			nodes: [7],
			edges: [114],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		LevelUsersByVoteManyToManyEdge: {
			cursor: [11],
			node: [7],
			votes: [
				89,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [92, '[VotesOrderBy!]'],
					condition: [93],
					filter: [48],
				},
			],
			__typename: [8],
		},
		RecordMedia: {
			nodeId: [2],
			id: [5],
			recordId: [5],
			ghostUrl: [8],
			dateCreated: [6],
			dateUpdated: [6],
			record: [60],
			__typename: [8],
		},
		RecordMediaConnection: {
			nodes: [115],
			edges: [117],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		RecordMediaEdge: {
			cursor: [11],
			node: [115],
			__typename: [8],
		},
		RecordMediaOrderBy: {},
		RecordMediaCondition: {
			id: [5],
			recordId: [5],
			ghostUrl: [8],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [8],
		},
		RecordUsersByPersonalBestGlobalManyToManyConnection: {
			nodes: [7],
			edges: [121],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		RecordUsersByPersonalBestGlobalManyToManyEdge: {
			cursor: [11],
			node: [7],
			personalBestGlobals: [
				58,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [78, '[PersonalBestGlobalsOrderBy!]'],
					condition: [79],
					filter: [23],
				},
			],
			__typename: [8],
		},
		RecordLevelsByPersonalBestGlobalManyToManyConnection: {
			nodes: [61],
			edges: [123],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		RecordLevelsByPersonalBestGlobalManyToManyEdge: {
			cursor: [11],
			node: [61],
			personalBestGlobals: [
				58,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [78, '[PersonalBestGlobalsOrderBy!]'],
					condition: [79],
					filter: [23],
				},
			],
			__typename: [8],
		},
		LevelsOrderBy: {},
		LevelCondition: {
			id: [5],
			hash: [8],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [8],
		},
		RecordLevelsByWorldRecordGlobalManyToManyConnection: {
			nodes: [61],
			edges: [127],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		RecordLevelsByWorldRecordGlobalManyToManyEdge: {
			cursor: [11],
			node: [61],
			worldRecordGlobals: [
				84,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [87, '[WorldRecordGlobalsOrderBy!]'],
					condition: [88],
					filter: [31],
				},
			],
			__typename: [8],
		},
		RecordUsersByWorldRecordGlobalManyToManyConnection: {
			nodes: [7],
			edges: [129],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		RecordUsersByWorldRecordGlobalManyToManyEdge: {
			cursor: [11],
			node: [7],
			worldRecordGlobals: [
				84,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [87, '[WorldRecordGlobalsOrderBy!]'],
					condition: [88],
					filter: [31],
				},
			],
			__typename: [8],
		},
		PersonalBestGlobalsEdge: {
			cursor: [11],
			node: [59],
			__typename: [8],
		},
		UserPointsConnection: {
			nodes: [132],
			edges: [133],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		UserPoint: {
			nodeId: [2],
			id: [5],
			userId: [5],
			points: [5],
			dateCreated: [6],
			dateUpdated: [6],
			rank: [5],
			worldRecords: [5],
			totalPoints: [5],
			user: [7],
			__typename: [8],
		},
		UserPointsEdge: {
			cursor: [11],
			node: [132],
			__typename: [8],
		},
		UserPointsOrderBy: {},
		UserPointCondition: {
			id: [5],
			userId: [5],
			points: [5],
			dateCreated: [6],
			dateUpdated: [6],
			rank: [5],
			worldRecords: [5],
			totalPoints: [5],
			__typename: [8],
		},
		UserPointsHistoriesConnection: {
			nodes: [137],
			edges: [138],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		UserPointsHistory: {
			nodeId: [2],
			id: [5],
			userId: [5],
			points: [5],
			totalPoints: [5],
			rank: [5],
			worldRecords: [5],
			dateCreated: [6],
			user: [7],
			__typename: [8],
		},
		UserPointsHistoriesEdge: {
			cursor: [11],
			node: [137],
			__typename: [8],
		},
		UserPointsHistoriesOrderBy: {},
		UserPointsHistoryCondition: {
			id: [5],
			userId: [5],
			points: [5],
			totalPoints: [5],
			rank: [5],
			worldRecords: [5],
			dateCreated: [6],
			__typename: [8],
		},
		UserLevelsByFavouriteManyToManyConnection: {
			nodes: [61],
			edges: [142],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		UserLevelsByFavouriteManyToManyEdge: {
			cursor: [11],
			node: [61],
			favourites: [
				3,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [12, '[FavouritesOrderBy!]'],
					condition: [13],
					filter: [14],
				},
			],
			__typename: [8],
		},
		UserRecordsByPersonalBestGlobalManyToManyConnection: {
			nodes: [60],
			edges: [144],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		UserRecordsByPersonalBestGlobalManyToManyEdge: {
			cursor: [11],
			node: [60],
			personalBestGlobals: [
				58,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [78, '[PersonalBestGlobalsOrderBy!]'],
					condition: [79],
					filter: [23],
				},
			],
			__typename: [8],
		},
		UserLevelsByPersonalBestGlobalManyToManyConnection: {
			nodes: [61],
			edges: [146],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		UserLevelsByPersonalBestGlobalManyToManyEdge: {
			cursor: [11],
			node: [61],
			personalBestGlobals: [
				58,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [78, '[PersonalBestGlobalsOrderBy!]'],
					condition: [79],
					filter: [23],
				},
			],
			__typename: [8],
		},
		UserLevelsByRecordManyToManyConnection: {
			nodes: [61],
			edges: [148],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		UserLevelsByRecordManyToManyEdge: {
			cursor: [11],
			node: [61],
			records: [
				80,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [82, '[RecordsOrderBy!]'],
					condition: [83],
					filter: [24],
				},
			],
			__typename: [8],
		},
		UserRecordsByWorldRecordGlobalManyToManyConnection: {
			nodes: [60],
			edges: [150],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		UserRecordsByWorldRecordGlobalManyToManyEdge: {
			cursor: [11],
			node: [60],
			worldRecordGlobals: [
				84,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [87, '[WorldRecordGlobalsOrderBy!]'],
					condition: [88],
					filter: [31],
				},
			],
			__typename: [8],
		},
		UserLevelsByWorldRecordGlobalManyToManyConnection: {
			nodes: [61],
			edges: [152],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		UserLevelsByWorldRecordGlobalManyToManyEdge: {
			cursor: [11],
			node: [61],
			worldRecordGlobals: [
				84,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [87, '[WorldRecordGlobalsOrderBy!]'],
					condition: [88],
					filter: [31],
				},
			],
			__typename: [8],
		},
		UserLevelsByVoteManyToManyConnection: {
			nodes: [61],
			edges: [154],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		UserLevelsByVoteManyToManyEdge: {
			cursor: [11],
			node: [61],
			votes: [
				89,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [92, '[VotesOrderBy!]'],
					condition: [93],
					filter: [48],
				},
			],
			__typename: [8],
		},
		FavouritesEdge: {
			cursor: [11],
			node: [4],
			__typename: [8],
		},
		LevelsConnection: {
			nodes: [61],
			edges: [157],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		LevelsEdge: {
			cursor: [11],
			node: [61],
			__typename: [8],
		},
		LevelRequestsConnection: {
			nodes: [159],
			edges: [160],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		LevelRequest: {
			nodeId: [2],
			id: [5],
			workshopId: [10],
			uid: [8],
			hash: [8],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [8],
		},
		LevelRequestsEdge: {
			cursor: [11],
			node: [159],
			__typename: [8],
		},
		LevelRequestsOrderBy: {},
		LevelRequestCondition: {
			id: [5],
			workshopId: [10],
			uid: [8],
			hash: [8],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [8],
		},
		LevelRequestFilter: {
			id: [15],
			workshopId: [20],
			uid: [18],
			hash: [18],
			dateCreated: [16],
			dateUpdated: [16],
			and: [163],
			or: [163],
			not: [163],
			__typename: [8],
		},
		UsersConnection: {
			nodes: [7],
			edges: [165],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		UsersEdge: {
			cursor: [11],
			node: [7],
			__typename: [8],
		},
		VersionsConnection: {
			nodes: [167],
			edges: [168],
			pageInfo: [65],
			totalCount: [5],
			__typename: [8],
		},
		Version: {
			nodeId: [2],
			id: [5],
			minimum: [8],
			latest: [8],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [8],
		},
		VersionsEdge: {
			cursor: [11],
			node: [167],
			__typename: [8],
		},
		VersionsOrderBy: {},
		VersionCondition: {
			id: [5],
			minimum: [8],
			latest: [8],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [8],
		},
		VersionFilter: {
			id: [15],
			minimum: [18],
			latest: [18],
			dateCreated: [16],
			dateUpdated: [16],
			and: [171],
			or: [171],
			not: [171],
			__typename: [8],
		},
		ZRtmConnection: {
			nodes: [173],
			edges: [174],
			totalCount: [5],
			__typename: [8],
		},
		ZRtmRecord: {
			id: [5],
			idLevel: [5],
			workshopId: [37],
			authorId: [37],
			name: [8],
			imageUrl: [8],
			fileAuthor: [8],
			fileUid: [8],
			validationTimeAuthor: [26],
			validationTimeGold: [26],
			validationTimeSilver: [26],
			validationTimeBronze: [26],
			deleted: [9],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			amountCheckpoints: [5],
			amountFinishes: [5],
			amountBlocks: [5],
			numRecords: [10],
			__typename: [8],
		},
		ZRtmEdge: {
			cursor: [11],
			node: [173],
			__typename: [8],
		},
		ZRtmRecordFilter: {
			id: [15],
			idLevel: [15],
			workshopId: [36],
			authorId: [36],
			name: [18],
			imageUrl: [18],
			fileAuthor: [18],
			fileUid: [18],
			validationTimeAuthor: [25],
			validationTimeGold: [25],
			validationTimeSilver: [25],
			validationTimeBronze: [25],
			deleted: [19],
			createdAt: [16],
			updatedAt: [16],
			dateCreated: [16],
			dateUpdated: [16],
			amountCheckpoints: [15],
			amountFinishes: [15],
			amountBlocks: [15],
			numRecords: [20],
			and: [175],
			or: [175],
			not: [175],
			__typename: [8],
		},
		Mutation: {
			updateWorldRecordGlobal: [
				177,
				{
					input: [178, 'UpdateWorldRecordGlobalInput!'],
				},
			],
			__typename: [8],
		},
		UpdateWorldRecordGlobalPayload: {
			clientMutationId: [8],
			query: [0],
			__typename: [8],
		},
		UpdateWorldRecordGlobalInput: {
			clientMutationId: [8],
			__typename: [8],
		},
		Subscription: {
			query: [0],
			nodeId: [2],
			node: [
				1,
				{
					nodeId: [2, 'ID!'],
				},
			],
			favourites: [
				3,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [12, '[FavouritesOrderBy!]'],
					condition: [13],
					filter: [14],
				},
			],
			levels: [
				156,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [124, '[LevelsOrderBy!]'],
					condition: [125],
					filter: [32],
				},
			],
			levelItems: [
				62,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [66, '[LevelItemsOrderBy!]'],
					condition: [67],
					filter: [35],
				},
			],
			levelMetadata: [
				68,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [71, '[LevelMetadataOrderBy!]'],
					condition: [72],
					filter: [39],
				},
			],
			levelPoints: [
				73,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [76, '[LevelPointsOrderBy!]'],
					condition: [77],
					filter: [43],
				},
			],
			levelPointsHistories: [
				94,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [97, '[LevelPointsHistoriesOrderBy!]'],
					condition: [98],
					filter: [50],
				},
			],
			levelRequests: [
				158,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [161, '[LevelRequestsOrderBy!]'],
					condition: [162],
					filter: [163],
				},
			],
			personalBestGlobals: [
				58,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [78, '[PersonalBestGlobalsOrderBy!]'],
					condition: [79],
					filter: [23],
				},
			],
			records: [
				80,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [82, '[RecordsOrderBy!]'],
					condition: [83],
					filter: [24],
				},
			],
			recordMedias: [
				116,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [118, '[RecordMediaOrderBy!]'],
					condition: [119],
					filter: [28],
				},
			],
			users: [
				164,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [101, '[UsersOrderBy!]'],
					condition: [102],
					filter: [17],
				},
			],
			userPoints: [
				131,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [134, '[UserPointsOrderBy!]'],
					condition: [135],
					filter: [52],
				},
			],
			userPointsHistories: [
				136,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [139, '[UserPointsHistoriesOrderBy!]'],
					condition: [140],
					filter: [57],
				},
			],
			versions: [
				166,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [169, '[VersionsOrderBy!]'],
					condition: [170],
					filter: [171],
				},
			],
			votes: [
				89,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [92, '[VotesOrderBy!]'],
					condition: [93],
					filter: [48],
				},
			],
			worldRecordGlobals: [
				84,
				{
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					orderBy: [87, '[WorldRecordGlobalsOrderBy!]'],
					condition: [88],
					filter: [31],
				},
			],
			favourite: [
				4,
				{
					id: [5, 'Int!'],
				},
			],
			level: [
				61,
				{
					id: [5, 'Int!'],
				},
			],
			levelByHash: [
				61,
				{
					hash: [8, 'String!'],
				},
			],
			levelItem: [
				63,
				{
					id: [5, 'Int!'],
				},
			],
			levelMetadatum: [
				69,
				{
					id: [5, 'Int!'],
				},
			],
			levelPoint: [
				74,
				{
					id: [5, 'Int!'],
				},
			],
			levelPointsHistory: [
				95,
				{
					id: [5, 'Int!'],
				},
			],
			levelRequest: [
				159,
				{
					id: [5, 'Int!'],
				},
			],
			personalBestGlobal: [
				59,
				{
					id: [5, 'Int!'],
				},
			],
			record: [
				60,
				{
					id: [5, 'Int!'],
				},
			],
			recordMedia: [
				115,
				{
					id: [5, 'Int!'],
				},
			],
			recordMediaByRecordId: [
				115,
				{
					recordId: [5, 'Int!'],
				},
			],
			user: [
				7,
				{
					id: [5, 'Int!'],
				},
			],
			userPoint: [
				132,
				{
					id: [5, 'Int!'],
				},
			],
			userPointsHistory: [
				137,
				{
					id: [5, 'Int!'],
				},
			],
			version: [
				167,
				{
					id: [5, 'Int!'],
				},
			],
			vote: [
				90,
				{
					id: [5, 'Int!'],
				},
			],
			worldRecordGlobal: [
				85,
				{
					id: [5, 'Int!'],
				},
			],
			zRtm: [
				172,
				{
					pMinAuthorTime: [26],
					pMaxAuthorTime: [26],
					pMinRecords: [5],
					pMaxRecords: [5],
					pExcludedAuthorIds: [5, '[Int]'],
					pExcludedHashes: [8, '[String]'],
					pMinCheckpoints: [5],
					pMaxCheckpoints: [5],
					pMinFinishes: [5],
					pMaxFinishes: [5],
					pMinBlocks: [5],
					pMaxBlocks: [5],
					pSampleSize: [5],
					first: [5],
					last: [5],
					offset: [5],
					before: [11],
					after: [11],
					filter: [175],
				},
			],
			favouriteByNodeId: [
				4,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelByNodeId: [
				61,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelItemByNodeId: [
				63,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelMetadatumByNodeId: [
				69,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelPointByNodeId: [
				74,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelPointsHistoryByNodeId: [
				95,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelRequestByNodeId: [
				159,
				{
					nodeId: [2, 'ID!'],
				},
			],
			personalBestGlobalByNodeId: [
				59,
				{
					nodeId: [2, 'ID!'],
				},
			],
			recordByNodeId: [
				60,
				{
					nodeId: [2, 'ID!'],
				},
			],
			recordMediaByNodeId: [
				115,
				{
					nodeId: [2, 'ID!'],
				},
			],
			userByNodeId: [
				7,
				{
					nodeId: [2, 'ID!'],
				},
			],
			userPointByNodeId: [
				132,
				{
					nodeId: [2, 'ID!'],
				},
			],
			userPointsHistoryByNodeId: [
				137,
				{
					nodeId: [2, 'ID!'],
				},
			],
			versionByNodeId: [
				167,
				{
					nodeId: [2, 'ID!'],
				},
			],
			voteByNodeId: [
				90,
				{
					nodeId: [2, 'ID!'],
				},
			],
			worldRecordGlobalByNodeId: [
				85,
				{
					nodeId: [2, 'ID!'],
				},
			],
			__typename: [8],
		},
	},
};
