export default {
	scalars: [
		2, 5, 6, 7, 9, 11, 12, 13, 22, 23, 35, 49, 71, 76, 81, 83, 87, 92, 97, 102,
		107, 113, 118, 123, 129, 135, 141, 147, 153, 159, 165, 171, 177, 183, 189,
		195, 201, 207, 212, 217,
	],
	types: {
		Query: {
			query: [0],
			nodeId: [2],
			node: [
				1,
				{
					nodeId: [2, 'ID!'],
				},
			],
			allVersionInfos: [
				3,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [13, '[VersionInfosOrderBy!]'],
					condition: [14],
					filter: [15],
				},
			],
			allFavorites: [
				19,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [23, '[FavoritesOrderBy!]'],
					condition: [24],
					filter: [25],
				},
			],
			allLevels: [
				116,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [118, '[LevelsOrderBy!]'],
					condition: [119],
					filter: [42],
				},
			],
			allLevelItems: [
				68,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [71, '[LevelItemsOrderBy!]'],
					condition: [72],
					filter: [45],
				},
			],
			allLevelMetadata: [
				73,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [76, '[LevelMetadataOrderBy!]'],
					condition: [77],
					filter: [47],
				},
			],
			allLevelPoints: [
				78,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [81, '[LevelPointsOrderBy!]'],
					condition: [82],
					filter: [51],
				},
			],
			allLevelRequests: [
				120,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [123, '[LevelRequestsOrderBy!]'],
					condition: [124],
					filter: [125],
				},
			],
			allPersonalBestGlobals: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			allRecords: [
				85,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [87, '[RecordsOrderBy!]'],
					condition: [88],
					filter: [33],
				},
			],
			allRecordMedias: [
				104,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [107, '[RecordMediasOrderBy!]'],
					condition: [108],
					filter: [38],
				},
			],
			allSampledFavorites: [
				126,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [129, '[SampledFavoritesOrderBy!]'],
					condition: [130],
					filter: [131],
				},
			],
			allSampledLevels: [
				132,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [135, '[SampledLevelsOrderBy!]'],
					condition: [136],
					filter: [137],
				},
			],
			allSampledLevelItems: [
				138,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [141, '[SampledLevelItemsOrderBy!]'],
					condition: [142],
					filter: [143],
				},
			],
			allSampledLevelMetadata: [
				144,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [147, '[SampledLevelMetadataOrderBy!]'],
					condition: [148],
					filter: [149],
				},
			],
			allSampledLevelPoints: [
				150,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [153, '[SampledLevelPointsOrderBy!]'],
					condition: [154],
					filter: [155],
				},
			],
			allSampledLevelRequests: [
				156,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [159, '[SampledLevelRequestsOrderBy!]'],
					condition: [160],
					filter: [161],
				},
			],
			allSampledPersonalBestGlobals: [
				162,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [165, '[SampledPersonalBestGlobalsOrderBy!]'],
					condition: [166],
					filter: [167],
				},
			],
			allSampledRecords: [
				168,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [171, '[SampledRecordsOrderBy!]'],
					condition: [172],
					filter: [173],
				},
			],
			allSampledRecordMedias: [
				174,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [177, '[SampledRecordMediasOrderBy!]'],
					condition: [178],
					filter: [179],
				},
			],
			allSampledUpvotes: [
				180,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [183, '[SampledUpvotesOrderBy!]'],
					condition: [184],
					filter: [185],
				},
			],
			allSampledUsers: [
				186,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [189, '[SampledUsersOrderBy!]'],
					condition: [190],
					filter: [191],
				},
			],
			allSampledUserPoints: [
				192,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [195, '[SampledUserPointsOrderBy!]'],
					condition: [196],
					filter: [197],
				},
			],
			allSampledVersions: [
				198,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [201, '[SampledVersionsOrderBy!]'],
					condition: [202],
					filter: [203],
				},
			],
			allSampledWorldRecordGlobals: [
				204,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [207, '[SampledWorldRecordGlobalsOrderBy!]'],
					condition: [208],
					filter: [209],
				},
			],
			allUpvotes: [
				89,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [92, '[UpvotesOrderBy!]'],
					condition: [93],
					filter: [55],
				},
			],
			allUsers: [
				210,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [212, '[UsersOrderBy!]'],
					condition: [213],
					filter: [27],
				},
			],
			allUserPoints: [
				110,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [113, '[UserPointsOrderBy!]'],
					condition: [114],
					filter: [60],
				},
			],
			allVersions: [
				214,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [217, '[VersionsOrderBy!]'],
					condition: [218],
					filter: [219],
				},
			],
			allVotes: [
				99,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [102, '[VotesOrderBy!]'],
					condition: [103],
					filter: [58],
				},
			],
			allWorldRecordGlobals: [
				94,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [97, '[WorldRecordGlobalsOrderBy!]'],
					condition: [98],
					filter: [41],
				},
			],
			favoriteById: [
				20,
				{
					id: [12, 'Int!'],
				},
			],
			levelById: [
				67,
				{
					id: [12, 'Int!'],
				},
			],
			levelByHash: [
				67,
				{
					hash: [7, 'String!'],
				},
			],
			levelItemById: [
				69,
				{
					id: [12, 'Int!'],
				},
			],
			levelMetadatumById: [
				74,
				{
					id: [12, 'Int!'],
				},
			],
			levelPointById: [
				79,
				{
					id: [12, 'Int!'],
				},
			],
			levelRequestById: [
				121,
				{
					id: [12, 'Int!'],
				},
			],
			personalBestGlobalById: [
				65,
				{
					id: [12, 'Int!'],
				},
			],
			recordById: [
				66,
				{
					id: [12, 'Int!'],
				},
			],
			recordMediaById: [
				105,
				{
					id: [12, 'Int!'],
				},
			],
			upvoteById: [
				90,
				{
					id: [12, 'Int!'],
				},
			],
			userById: [
				21,
				{
					id: [12, 'Int!'],
				},
			],
			userPointById: [
				111,
				{
					id: [12, 'Int!'],
				},
			],
			versionById: [
				215,
				{
					id: [12, 'Int!'],
				},
			],
			voteById: [
				100,
				{
					id: [12, 'Int!'],
				},
			],
			worldRecordGlobalById: [
				95,
				{
					id: [12, 'Int!'],
				},
			],
			zRtm: [
				220,
				{
					pMinAuthorTime: [35],
					pMaxAuthorTime: [35],
					pMinRecords: [12],
					pMaxRecords: [12],
					pExcludedAuthorIds: [12, '[Int]'],
					pExcludedHashes: [7, '[String]'],
					pMinCheckpoints: [12],
					pMaxCheckpoints: [12],
					pMinFinishes: [12],
					pMaxFinishes: [12],
					pMinBlocks: [12],
					pMaxBlocks: [12],
					pSampleSize: [12],
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					filter: [223],
				},
			],
			favorite: [
				20,
				{
					nodeId: [2, 'ID!'],
				},
			],
			level: [
				67,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelItem: [
				69,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelMetadatum: [
				74,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelPoint: [
				79,
				{
					nodeId: [2, 'ID!'],
				},
			],
			levelRequest: [
				121,
				{
					nodeId: [2, 'ID!'],
				},
			],
			personalBestGlobal: [
				65,
				{
					nodeId: [2, 'ID!'],
				},
			],
			record: [
				66,
				{
					nodeId: [2, 'ID!'],
				},
			],
			recordMedia: [
				105,
				{
					nodeId: [2, 'ID!'],
				},
			],
			upvote: [
				90,
				{
					nodeId: [2, 'ID!'],
				},
			],
			user: [
				21,
				{
					nodeId: [2, 'ID!'],
				},
			],
			userPoint: [
				111,
				{
					nodeId: [2, 'ID!'],
				},
			],
			version: [
				215,
				{
					nodeId: [2, 'ID!'],
				},
			],
			vote: [
				100,
				{
					nodeId: [2, 'ID!'],
				},
			],
			worldRecordGlobal: [
				95,
				{
					nodeId: [2, 'ID!'],
				},
			],
			__typename: [7],
		},
		Node: {
			nodeId: [2],
			on_Query: [0],
			on_Favorite: [20],
			on_User: [21],
			on_PersonalBestGlobal: [65],
			on_Record: [66],
			on_Level: [67],
			on_LevelItem: [69],
			on_LevelMetadatum: [74],
			on_LevelPoint: [79],
			on_Upvote: [90],
			on_WorldRecordGlobal: [95],
			on_Vote: [100],
			on_RecordMedia: [105],
			on_UserPoint: [111],
			on_LevelRequest: [121],
			on_Version: [215],
			__typename: [7],
		},
		ID: {},
		VersionInfosConnection: {
			nodes: [4],
			edges: [8],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		VersionInfo: {
			version: [5],
			appliedOn: [6],
			description: [7],
			__typename: [7],
		},
		BigInt: {},
		Datetime: {},
		String: {},
		VersionInfosEdge: {
			cursor: [9],
			node: [4],
			__typename: [7],
		},
		Cursor: {},
		PageInfo: {
			hasNextPage: [11],
			hasPreviousPage: [11],
			startCursor: [9],
			endCursor: [9],
			__typename: [7],
		},
		Boolean: {},
		Int: {},
		VersionInfosOrderBy: {},
		VersionInfoCondition: {
			version: [5],
			appliedOn: [6],
			description: [7],
			__typename: [7],
		},
		VersionInfoFilter: {
			version: [16],
			appliedOn: [17],
			description: [18],
			and: [15],
			or: [15],
			not: [15],
			__typename: [7],
		},
		BigIntFilter: {
			isNull: [11],
			equalTo: [5],
			notEqualTo: [5],
			distinctFrom: [5],
			notDistinctFrom: [5],
			in: [5],
			notIn: [5],
			lessThan: [5],
			lessThanOrEqualTo: [5],
			greaterThan: [5],
			greaterThanOrEqualTo: [5],
			__typename: [7],
		},
		DatetimeFilter: {
			isNull: [11],
			equalTo: [6],
			notEqualTo: [6],
			distinctFrom: [6],
			notDistinctFrom: [6],
			in: [6],
			notIn: [6],
			lessThan: [6],
			lessThanOrEqualTo: [6],
			greaterThan: [6],
			greaterThanOrEqualTo: [6],
			__typename: [7],
		},
		StringFilter: {
			isNull: [11],
			equalTo: [7],
			notEqualTo: [7],
			distinctFrom: [7],
			notDistinctFrom: [7],
			in: [7],
			notIn: [7],
			lessThan: [7],
			lessThanOrEqualTo: [7],
			greaterThan: [7],
			greaterThanOrEqualTo: [7],
			includes: [7],
			notIncludes: [7],
			includesInsensitive: [7],
			notIncludesInsensitive: [7],
			startsWith: [7],
			notStartsWith: [7],
			startsWithInsensitive: [7],
			notStartsWithInsensitive: [7],
			endsWith: [7],
			notEndsWith: [7],
			endsWithInsensitive: [7],
			notEndsWithInsensitive: [7],
			like: [7],
			notLike: [7],
			likeInsensitive: [7],
			notLikeInsensitive: [7],
			equalToInsensitive: [7],
			notEqualToInsensitive: [7],
			distinctFromInsensitive: [7],
			notDistinctFromInsensitive: [7],
			inInsensitive: [7],
			notInInsensitive: [7],
			lessThanInsensitive: [7],
			lessThanOrEqualToInsensitive: [7],
			greaterThanInsensitive: [7],
			greaterThanOrEqualToInsensitive: [7],
			__typename: [7],
		},
		FavoritesConnection: {
			nodes: [20],
			edges: [115],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		Favorite: {
			nodeId: [2],
			id: [12],
			idUser: [12],
			dateCreated: [6],
			dateUpdated: [6],
			idLevel: [12],
			userByIdUser: [21],
			levelByIdLevel: [67],
			__typename: [7],
		},
		User: {
			nodeId: [2],
			id: [12],
			steamName: [7],
			banned: [11],
			dateCreated: [6],
			dateUpdated: [6],
			steamId: [22],
			discordId: [22],
			favoritesByIdUser: [
				19,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [23, '[FavoritesOrderBy!]'],
					condition: [24],
					filter: [25],
				},
			],
			personalBestGlobalsByIdUser: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			userPointsByIdUser: [
				110,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [113, '[UserPointsOrderBy!]'],
					condition: [114],
					filter: [60],
				},
			],
			recordsByIdUser: [
				85,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [87, '[RecordsOrderBy!]'],
					condition: [88],
					filter: [33],
				},
			],
			upvotesByIdUser: [
				89,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [92, '[UpvotesOrderBy!]'],
					condition: [93],
					filter: [55],
				},
			],
			votesByIdUser: [
				99,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [102, '[VotesOrderBy!]'],
					condition: [103],
					filter: [58],
				},
			],
			__typename: [7],
		},
		BigFloat: {},
		FavoritesOrderBy: {},
		FavoriteCondition: {
			id: [12],
			idUser: [12],
			dateCreated: [6],
			dateUpdated: [6],
			idLevel: [12],
			__typename: [7],
		},
		FavoriteFilter: {
			id: [26],
			idUser: [26],
			dateCreated: [17],
			dateUpdated: [17],
			idLevel: [26],
			userByIdUser: [27],
			levelByIdLevel: [42],
			and: [25],
			or: [25],
			not: [25],
			__typename: [7],
		},
		IntFilter: {
			isNull: [11],
			equalTo: [12],
			notEqualTo: [12],
			distinctFrom: [12],
			notDistinctFrom: [12],
			in: [12],
			notIn: [12],
			lessThan: [12],
			lessThanOrEqualTo: [12],
			greaterThan: [12],
			greaterThanOrEqualTo: [12],
			__typename: [7],
		},
		UserFilter: {
			id: [26],
			steamName: [18],
			banned: [28],
			dateCreated: [17],
			dateUpdated: [17],
			steamId: [29],
			discordId: [29],
			favoritesByIdUserList: [30],
			favoritesByIdUserListExist: [11],
			personalBestGlobalsByIdUserList: [31],
			personalBestGlobalsByIdUserListExist: [11],
			userPointsByIdUserList: [59],
			userPointsByIdUserListExist: [11],
			recordsByIdUserList: [61],
			recordsByIdUserListExist: [11],
			upvotesByIdUserList: [62],
			upvotesByIdUserListExist: [11],
			votesByIdUserList: [63],
			votesByIdUserListExist: [11],
			and: [27],
			or: [27],
			not: [27],
			__typename: [7],
		},
		BooleanFilter: {
			isNull: [11],
			equalTo: [11],
			notEqualTo: [11],
			distinctFrom: [11],
			notDistinctFrom: [11],
			in: [11],
			notIn: [11],
			lessThan: [11],
			lessThanOrEqualTo: [11],
			greaterThan: [11],
			greaterThanOrEqualTo: [11],
			__typename: [7],
		},
		BigFloatFilter: {
			isNull: [11],
			equalTo: [22],
			notEqualTo: [22],
			distinctFrom: [22],
			notDistinctFrom: [22],
			in: [22],
			notIn: [22],
			lessThan: [22],
			lessThanOrEqualTo: [22],
			greaterThan: [22],
			greaterThanOrEqualTo: [22],
			__typename: [7],
		},
		UserToManyFavoriteFilter: {
			every: [25],
			some: [25],
			none: [25],
			__typename: [7],
		},
		UserToManyPersonalBestGlobalFilter: {
			every: [32],
			some: [32],
			none: [32],
			__typename: [7],
		},
		PersonalBestGlobalFilter: {
			id: [26],
			idRecord: [26],
			idUser: [26],
			idLevel: [26],
			dateCreated: [17],
			dateUpdated: [17],
			recordByIdRecord: [33],
			userByIdUser: [27],
			levelByIdLevel: [42],
			and: [32],
			or: [32],
			not: [32],
			__typename: [7],
		},
		RecordFilter: {
			id: [26],
			idUser: [26],
			time: [34],
			gameVersion: [18],
			idLevel: [26],
			modVersion: [18],
			dateCreated: [17],
			dateUpdated: [17],
			splits: [36],
			speeds: [36],
			recordMediasByIdRecordList: [37],
			recordMediasByIdRecordListExist: [11],
			personalBestGlobalsByIdRecordList: [39],
			personalBestGlobalsByIdRecordListExist: [11],
			worldRecordGlobalsByIdRecordList: [40],
			worldRecordGlobalsByIdRecordListExist: [11],
			userByIdUser: [27],
			levelByIdLevel: [42],
			and: [33],
			or: [33],
			not: [33],
			__typename: [7],
		},
		FloatFilter: {
			isNull: [11],
			equalTo: [35],
			notEqualTo: [35],
			distinctFrom: [35],
			notDistinctFrom: [35],
			in: [35],
			notIn: [35],
			lessThan: [35],
			lessThanOrEqualTo: [35],
			greaterThan: [35],
			greaterThanOrEqualTo: [35],
			__typename: [7],
		},
		Float: {},
		FloatListFilter: {
			isNull: [11],
			equalTo: [35],
			notEqualTo: [35],
			distinctFrom: [35],
			notDistinctFrom: [35],
			lessThan: [35],
			lessThanOrEqualTo: [35],
			greaterThan: [35],
			greaterThanOrEqualTo: [35],
			contains: [35],
			containedBy: [35],
			overlaps: [35],
			anyEqualTo: [35],
			anyNotEqualTo: [35],
			anyLessThan: [35],
			anyLessThanOrEqualTo: [35],
			anyGreaterThan: [35],
			anyGreaterThanOrEqualTo: [35],
			__typename: [7],
		},
		RecordToManyRecordMediaFilter: {
			every: [38],
			some: [38],
			none: [38],
			__typename: [7],
		},
		RecordMediaFilter: {
			id: [26],
			idRecord: [26],
			ghostUrl: [18],
			dateCreated: [17],
			dateUpdated: [17],
			recordByIdRecord: [33],
			and: [38],
			or: [38],
			not: [38],
			__typename: [7],
		},
		RecordToManyPersonalBestGlobalFilter: {
			every: [32],
			some: [32],
			none: [32],
			__typename: [7],
		},
		RecordToManyWorldRecordGlobalFilter: {
			every: [41],
			some: [41],
			none: [41],
			__typename: [7],
		},
		WorldRecordGlobalFilter: {
			id: [26],
			idRecord: [26],
			idLevel: [26],
			dateCreated: [17],
			dateUpdated: [17],
			recordByIdRecord: [33],
			levelByIdLevel: [42],
			and: [41],
			or: [41],
			not: [41],
			__typename: [7],
		},
		LevelFilter: {
			id: [26],
			hash: [18],
			dateCreated: [17],
			dateUpdated: [17],
			favoritesByIdLevelList: [43],
			favoritesByIdLevelListExist: [11],
			levelItemsByIdLevelList: [44],
			levelItemsByIdLevelListExist: [11],
			levelMetadataByIdLevelList: [46],
			levelMetadataByIdLevelListExist: [11],
			levelPointsByIdLevelList: [50],
			levelPointsByIdLevelListExist: [11],
			personalBestGlobalsByIdLevelList: [52],
			personalBestGlobalsByIdLevelListExist: [11],
			recordsByIdLevelList: [53],
			recordsByIdLevelListExist: [11],
			upvotesByIdLevelList: [54],
			upvotesByIdLevelListExist: [11],
			worldRecordGlobalsByIdLevelList: [56],
			worldRecordGlobalsByIdLevelListExist: [11],
			votesByIdLevelList: [57],
			votesByIdLevelListExist: [11],
			and: [42],
			or: [42],
			not: [42],
			__typename: [7],
		},
		LevelToManyFavoriteFilter: {
			every: [25],
			some: [25],
			none: [25],
			__typename: [7],
		},
		LevelToManyLevelItemFilter: {
			every: [45],
			some: [45],
			none: [45],
			__typename: [7],
		},
		LevelItemFilter: {
			id: [26],
			idLevel: [26],
			workshopId: [29],
			authorId: [29],
			name: [18],
			imageUrl: [18],
			fileAuthor: [18],
			fileUid: [18],
			validationTimeAuthor: [34],
			validationTimeGold: [34],
			validationTimeSilver: [34],
			validationTimeBronze: [34],
			deleted: [28],
			createdAt: [17],
			updatedAt: [17],
			dateCreated: [17],
			dateUpdated: [17],
			levelByIdLevel: [42],
			and: [45],
			or: [45],
			not: [45],
			__typename: [7],
		},
		LevelToManyLevelMetadatumFilter: {
			every: [47],
			some: [47],
			none: [47],
			__typename: [7],
		},
		LevelMetadatumFilter: {
			id: [26],
			idLevel: [26],
			amountCheckpoints: [26],
			amountFinishes: [26],
			amountBlocks: [26],
			typeGround: [26],
			typeSkybox: [26],
			blocks: [48],
			dateCreated: [17],
			dateUpdated: [17],
			levelByIdLevel: [42],
			and: [47],
			or: [47],
			not: [47],
			__typename: [7],
		},
		JSONFilter: {
			isNull: [11],
			equalTo: [49],
			notEqualTo: [49],
			distinctFrom: [49],
			notDistinctFrom: [49],
			in: [49],
			notIn: [49],
			lessThan: [49],
			lessThanOrEqualTo: [49],
			greaterThan: [49],
			greaterThanOrEqualTo: [49],
			contains: [49],
			containsKey: [7],
			containsAllKeys: [7],
			containsAnyKeys: [7],
			containedBy: [49],
			__typename: [7],
		},
		JSON: {},
		LevelToManyLevelPointFilter: {
			every: [51],
			some: [51],
			none: [51],
			__typename: [7],
		},
		LevelPointFilter: {
			id: [26],
			points: [26],
			idLevel: [26],
			dateCreated: [17],
			dateUpdated: [17],
			levelByIdLevel: [42],
			and: [51],
			or: [51],
			not: [51],
			__typename: [7],
		},
		LevelToManyPersonalBestGlobalFilter: {
			every: [32],
			some: [32],
			none: [32],
			__typename: [7],
		},
		LevelToManyRecordFilter: {
			every: [33],
			some: [33],
			none: [33],
			__typename: [7],
		},
		LevelToManyUpvoteFilter: {
			every: [55],
			some: [55],
			none: [55],
			__typename: [7],
		},
		UpvoteFilter: {
			id: [26],
			idUser: [26],
			idLevel: [26],
			dateCreated: [17],
			dateUpdated: [17],
			userByIdUser: [27],
			levelByIdLevel: [42],
			and: [55],
			or: [55],
			not: [55],
			__typename: [7],
		},
		LevelToManyWorldRecordGlobalFilter: {
			every: [41],
			some: [41],
			none: [41],
			__typename: [7],
		},
		LevelToManyVoteFilter: {
			every: [58],
			some: [58],
			none: [58],
			__typename: [7],
		},
		VoteFilter: {
			id: [26],
			idUser: [26],
			idLevel: [26],
			value: [26],
			dateCreated: [17],
			dateUpdated: [17],
			userByIdUser: [27],
			levelByIdLevel: [42],
			and: [58],
			or: [58],
			not: [58],
			__typename: [7],
		},
		UserToManyUserPointFilter: {
			every: [60],
			some: [60],
			none: [60],
			__typename: [7],
		},
		UserPointFilter: {
			id: [26],
			idUser: [26],
			points: [26],
			dateCreated: [17],
			dateUpdated: [17],
			rank: [26],
			worldRecords: [26],
			userByIdUser: [27],
			and: [60],
			or: [60],
			not: [60],
			__typename: [7],
		},
		UserToManyRecordFilter: {
			every: [33],
			some: [33],
			none: [33],
			__typename: [7],
		},
		UserToManyUpvoteFilter: {
			every: [55],
			some: [55],
			none: [55],
			__typename: [7],
		},
		UserToManyVoteFilter: {
			every: [58],
			some: [58],
			none: [58],
			__typename: [7],
		},
		PersonalBestGlobalsConnection: {
			nodes: [65],
			edges: [109],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		PersonalBestGlobal: {
			nodeId: [2],
			id: [12],
			idRecord: [12],
			idUser: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			recordByIdRecord: [66],
			userByIdUser: [21],
			levelByIdLevel: [67],
			__typename: [7],
		},
		Record: {
			nodeId: [2],
			id: [12],
			idUser: [12],
			time: [35],
			gameVersion: [7],
			idLevel: [12],
			modVersion: [7],
			dateCreated: [6],
			dateUpdated: [6],
			splits: [35],
			speeds: [35],
			userByIdUser: [21],
			levelByIdLevel: [67],
			recordMediasByIdRecord: [
				104,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [107, '[RecordMediasOrderBy!]'],
					condition: [108],
					filter: [38],
				},
			],
			personalBestGlobalsByIdRecord: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			worldRecordGlobalsByIdRecord: [
				94,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [97, '[WorldRecordGlobalsOrderBy!]'],
					condition: [98],
					filter: [41],
				},
			],
			__typename: [7],
		},
		Level: {
			nodeId: [2],
			id: [12],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			favoritesByIdLevel: [
				19,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [23, '[FavoritesOrderBy!]'],
					condition: [24],
					filter: [25],
				},
			],
			levelItemsByIdLevel: [
				68,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [71, '[LevelItemsOrderBy!]'],
					condition: [72],
					filter: [45],
				},
			],
			levelMetadataByIdLevel: [
				73,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [76, '[LevelMetadataOrderBy!]'],
					condition: [77],
					filter: [47],
				},
			],
			levelPointsByIdLevel: [
				78,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [81, '[LevelPointsOrderBy!]'],
					condition: [82],
					filter: [51],
				},
			],
			personalBestGlobalsByIdLevel: [
				64,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [83, '[PersonalBestGlobalsOrderBy!]'],
					condition: [84],
					filter: [32],
				},
			],
			recordsByIdLevel: [
				85,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [87, '[RecordsOrderBy!]'],
					condition: [88],
					filter: [33],
				},
			],
			upvotesByIdLevel: [
				89,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [92, '[UpvotesOrderBy!]'],
					condition: [93],
					filter: [55],
				},
			],
			worldRecordGlobalsByIdLevel: [
				94,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [97, '[WorldRecordGlobalsOrderBy!]'],
					condition: [98],
					filter: [41],
				},
			],
			votesByIdLevel: [
				99,
				{
					first: [12],
					last: [12],
					offset: [12],
					before: [9],
					after: [9],
					orderBy: [102, '[VotesOrderBy!]'],
					condition: [103],
					filter: [58],
				},
			],
			__typename: [7],
		},
		LevelItemsConnection: {
			nodes: [69],
			edges: [70],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelItem: {
			nodeId: [2],
			id: [12],
			idLevel: [12],
			workshopId: [22],
			authorId: [22],
			name: [7],
			imageUrl: [7],
			fileAuthor: [7],
			fileUid: [7],
			validationTimeAuthor: [35],
			validationTimeGold: [35],
			validationTimeSilver: [35],
			validationTimeBronze: [35],
			deleted: [11],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			levelByIdLevel: [67],
			__typename: [7],
		},
		LevelItemsEdge: {
			cursor: [9],
			node: [69],
			__typename: [7],
		},
		LevelItemsOrderBy: {},
		LevelItemCondition: {
			id: [12],
			idLevel: [12],
			workshopId: [22],
			authorId: [22],
			name: [7],
			imageUrl: [7],
			fileAuthor: [7],
			fileUid: [7],
			validationTimeAuthor: [35],
			validationTimeGold: [35],
			validationTimeSilver: [35],
			validationTimeBronze: [35],
			deleted: [11],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelMetadataConnection: {
			nodes: [74],
			edges: [75],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelMetadatum: {
			nodeId: [2],
			id: [12],
			idLevel: [12],
			amountCheckpoints: [12],
			amountFinishes: [12],
			amountBlocks: [12],
			typeGround: [12],
			typeSkybox: [12],
			blocks: [49],
			dateCreated: [6],
			dateUpdated: [6],
			levelByIdLevel: [67],
			__typename: [7],
		},
		LevelMetadataEdge: {
			cursor: [9],
			node: [74],
			__typename: [7],
		},
		LevelMetadataOrderBy: {},
		LevelMetadatumCondition: {
			id: [12],
			idLevel: [12],
			amountCheckpoints: [12],
			amountFinishes: [12],
			amountBlocks: [12],
			typeGround: [12],
			typeSkybox: [12],
			blocks: [49],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelPointsConnection: {
			nodes: [79],
			edges: [80],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelPoint: {
			nodeId: [2],
			id: [12],
			points: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			levelByIdLevel: [67],
			__typename: [7],
		},
		LevelPointsEdge: {
			cursor: [9],
			node: [79],
			__typename: [7],
		},
		LevelPointsOrderBy: {},
		LevelPointCondition: {
			id: [12],
			points: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		PersonalBestGlobalsOrderBy: {},
		PersonalBestGlobalCondition: {
			id: [12],
			idRecord: [12],
			idUser: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		RecordsConnection: {
			nodes: [66],
			edges: [86],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		RecordsEdge: {
			cursor: [9],
			node: [66],
			__typename: [7],
		},
		RecordsOrderBy: {},
		RecordCondition: {
			id: [12],
			idUser: [12],
			time: [35],
			gameVersion: [7],
			idLevel: [12],
			modVersion: [7],
			dateCreated: [6],
			dateUpdated: [6],
			splits: [35],
			speeds: [35],
			__typename: [7],
		},
		UpvotesConnection: {
			nodes: [90],
			edges: [91],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		Upvote: {
			nodeId: [2],
			id: [12],
			idUser: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			userByIdUser: [21],
			levelByIdLevel: [67],
			__typename: [7],
		},
		UpvotesEdge: {
			cursor: [9],
			node: [90],
			__typename: [7],
		},
		UpvotesOrderBy: {},
		UpvoteCondition: {
			id: [12],
			idUser: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		WorldRecordGlobalsConnection: {
			nodes: [95],
			edges: [96],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		WorldRecordGlobal: {
			nodeId: [2],
			id: [12],
			idRecord: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			recordByIdRecord: [66],
			levelByIdLevel: [67],
			__typename: [7],
		},
		WorldRecordGlobalsEdge: {
			cursor: [9],
			node: [95],
			__typename: [7],
		},
		WorldRecordGlobalsOrderBy: {},
		WorldRecordGlobalCondition: {
			id: [12],
			idRecord: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		VotesConnection: {
			nodes: [100],
			edges: [101],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		Vote: {
			nodeId: [2],
			id: [12],
			idUser: [12],
			idLevel: [12],
			value: [12],
			dateCreated: [6],
			dateUpdated: [6],
			userByIdUser: [21],
			levelByIdLevel: [67],
			__typename: [7],
		},
		VotesEdge: {
			cursor: [9],
			node: [100],
			__typename: [7],
		},
		VotesOrderBy: {},
		VoteCondition: {
			id: [12],
			idUser: [12],
			idLevel: [12],
			value: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		RecordMediasConnection: {
			nodes: [105],
			edges: [106],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		RecordMedia: {
			nodeId: [2],
			id: [12],
			idRecord: [12],
			ghostUrl: [7],
			dateCreated: [6],
			dateUpdated: [6],
			recordByIdRecord: [66],
			__typename: [7],
		},
		RecordMediasEdge: {
			cursor: [9],
			node: [105],
			__typename: [7],
		},
		RecordMediasOrderBy: {},
		RecordMediaCondition: {
			id: [12],
			idRecord: [12],
			ghostUrl: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		PersonalBestGlobalsEdge: {
			cursor: [9],
			node: [65],
			__typename: [7],
		},
		UserPointsConnection: {
			nodes: [111],
			edges: [112],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		UserPoint: {
			nodeId: [2],
			id: [12],
			idUser: [12],
			points: [12],
			dateCreated: [6],
			dateUpdated: [6],
			rank: [12],
			worldRecords: [12],
			userByIdUser: [21],
			__typename: [7],
		},
		UserPointsEdge: {
			cursor: [9],
			node: [111],
			__typename: [7],
		},
		UserPointsOrderBy: {},
		UserPointCondition: {
			id: [12],
			idUser: [12],
			points: [12],
			dateCreated: [6],
			dateUpdated: [6],
			rank: [12],
			worldRecords: [12],
			__typename: [7],
		},
		FavoritesEdge: {
			cursor: [9],
			node: [20],
			__typename: [7],
		},
		LevelsConnection: {
			nodes: [67],
			edges: [117],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelsEdge: {
			cursor: [9],
			node: [67],
			__typename: [7],
		},
		LevelsOrderBy: {},
		LevelCondition: {
			id: [12],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelRequestsConnection: {
			nodes: [121],
			edges: [122],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		LevelRequest: {
			nodeId: [2],
			id: [12],
			workshopId: [22],
			uid: [7],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelRequestsEdge: {
			cursor: [9],
			node: [121],
			__typename: [7],
		},
		LevelRequestsOrderBy: {},
		LevelRequestCondition: {
			id: [12],
			workshopId: [22],
			uid: [7],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		LevelRequestFilter: {
			id: [26],
			workshopId: [29],
			uid: [18],
			hash: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [125],
			or: [125],
			not: [125],
			__typename: [7],
		},
		SampledFavoritesConnection: {
			nodes: [127],
			edges: [128],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledFavorite: {
			id: [12],
			idUser: [12],
			dateCreated: [6],
			dateUpdated: [6],
			idLevel: [12],
			__typename: [7],
		},
		SampledFavoritesEdge: {
			cursor: [9],
			node: [127],
			__typename: [7],
		},
		SampledFavoritesOrderBy: {},
		SampledFavoriteCondition: {
			id: [12],
			idUser: [12],
			dateCreated: [6],
			dateUpdated: [6],
			idLevel: [12],
			__typename: [7],
		},
		SampledFavoriteFilter: {
			id: [26],
			idUser: [26],
			dateCreated: [17],
			dateUpdated: [17],
			idLevel: [26],
			and: [131],
			or: [131],
			not: [131],
			__typename: [7],
		},
		SampledLevelsConnection: {
			nodes: [133],
			edges: [134],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledLevel: {
			id: [12],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelsEdge: {
			cursor: [9],
			node: [133],
			__typename: [7],
		},
		SampledLevelsOrderBy: {},
		SampledLevelCondition: {
			id: [12],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelFilter: {
			id: [26],
			hash: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [137],
			or: [137],
			not: [137],
			__typename: [7],
		},
		SampledLevelItemsConnection: {
			nodes: [139],
			edges: [140],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledLevelItem: {
			id: [12],
			idLevel: [12],
			workshopId: [22],
			authorId: [22],
			name: [7],
			imageUrl: [7],
			fileAuthor: [7],
			fileUid: [7],
			validationTimeAuthor: [35],
			validationTimeGold: [35],
			validationTimeSilver: [35],
			validationTimeBronze: [35],
			deleted: [11],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelItemsEdge: {
			cursor: [9],
			node: [139],
			__typename: [7],
		},
		SampledLevelItemsOrderBy: {},
		SampledLevelItemCondition: {
			id: [12],
			idLevel: [12],
			workshopId: [22],
			authorId: [22],
			name: [7],
			imageUrl: [7],
			fileAuthor: [7],
			fileUid: [7],
			validationTimeAuthor: [35],
			validationTimeGold: [35],
			validationTimeSilver: [35],
			validationTimeBronze: [35],
			deleted: [11],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelItemFilter: {
			id: [26],
			idLevel: [26],
			workshopId: [29],
			authorId: [29],
			name: [18],
			imageUrl: [18],
			fileAuthor: [18],
			fileUid: [18],
			validationTimeAuthor: [34],
			validationTimeGold: [34],
			validationTimeSilver: [34],
			validationTimeBronze: [34],
			deleted: [28],
			createdAt: [17],
			updatedAt: [17],
			dateCreated: [17],
			dateUpdated: [17],
			and: [143],
			or: [143],
			not: [143],
			__typename: [7],
		},
		SampledLevelMetadataConnection: {
			nodes: [145],
			edges: [146],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledLevelMetadatum: {
			id: [12],
			idLevel: [12],
			amountCheckpoints: [12],
			amountFinishes: [12],
			amountBlocks: [12],
			typeGround: [12],
			typeSkybox: [12],
			blocks: [49],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelMetadataEdge: {
			cursor: [9],
			node: [145],
			__typename: [7],
		},
		SampledLevelMetadataOrderBy: {},
		SampledLevelMetadatumCondition: {
			id: [12],
			idLevel: [12],
			amountCheckpoints: [12],
			amountFinishes: [12],
			amountBlocks: [12],
			typeGround: [12],
			typeSkybox: [12],
			blocks: [49],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelMetadatumFilter: {
			id: [26],
			idLevel: [26],
			amountCheckpoints: [26],
			amountFinishes: [26],
			amountBlocks: [26],
			typeGround: [26],
			typeSkybox: [26],
			blocks: [48],
			dateCreated: [17],
			dateUpdated: [17],
			and: [149],
			or: [149],
			not: [149],
			__typename: [7],
		},
		SampledLevelPointsConnection: {
			nodes: [151],
			edges: [152],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledLevelPoint: {
			id: [12],
			points: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelPointsEdge: {
			cursor: [9],
			node: [151],
			__typename: [7],
		},
		SampledLevelPointsOrderBy: {},
		SampledLevelPointCondition: {
			id: [12],
			points: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelPointFilter: {
			id: [26],
			points: [26],
			idLevel: [26],
			dateCreated: [17],
			dateUpdated: [17],
			and: [155],
			or: [155],
			not: [155],
			__typename: [7],
		},
		SampledLevelRequestsConnection: {
			nodes: [157],
			edges: [158],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledLevelRequest: {
			id: [12],
			workshopId: [22],
			uid: [7],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelRequestsEdge: {
			cursor: [9],
			node: [157],
			__typename: [7],
		},
		SampledLevelRequestsOrderBy: {},
		SampledLevelRequestCondition: {
			id: [12],
			workshopId: [22],
			uid: [7],
			hash: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledLevelRequestFilter: {
			id: [26],
			workshopId: [29],
			uid: [18],
			hash: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [161],
			or: [161],
			not: [161],
			__typename: [7],
		},
		SampledPersonalBestGlobalsConnection: {
			nodes: [163],
			edges: [164],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledPersonalBestGlobal: {
			id: [12],
			idRecord: [12],
			idUser: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledPersonalBestGlobalsEdge: {
			cursor: [9],
			node: [163],
			__typename: [7],
		},
		SampledPersonalBestGlobalsOrderBy: {},
		SampledPersonalBestGlobalCondition: {
			id: [12],
			idRecord: [12],
			idUser: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledPersonalBestGlobalFilter: {
			id: [26],
			idRecord: [26],
			idUser: [26],
			idLevel: [26],
			dateCreated: [17],
			dateUpdated: [17],
			and: [167],
			or: [167],
			not: [167],
			__typename: [7],
		},
		SampledRecordsConnection: {
			nodes: [169],
			edges: [170],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledRecord: {
			id: [12],
			idUser: [12],
			time: [35],
			gameVersion: [7],
			idLevel: [12],
			modVersion: [7],
			dateCreated: [6],
			dateUpdated: [6],
			splits: [35],
			speeds: [35],
			__typename: [7],
		},
		SampledRecordsEdge: {
			cursor: [9],
			node: [169],
			__typename: [7],
		},
		SampledRecordsOrderBy: {},
		SampledRecordCondition: {
			id: [12],
			idUser: [12],
			time: [35],
			gameVersion: [7],
			idLevel: [12],
			modVersion: [7],
			dateCreated: [6],
			dateUpdated: [6],
			splits: [35],
			speeds: [35],
			__typename: [7],
		},
		SampledRecordFilter: {
			id: [26],
			idUser: [26],
			time: [34],
			gameVersion: [18],
			idLevel: [26],
			modVersion: [18],
			dateCreated: [17],
			dateUpdated: [17],
			splits: [36],
			speeds: [36],
			and: [173],
			or: [173],
			not: [173],
			__typename: [7],
		},
		SampledRecordMediasConnection: {
			nodes: [175],
			edges: [176],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledRecordMedia: {
			id: [12],
			idRecord: [12],
			ghostUrl: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledRecordMediasEdge: {
			cursor: [9],
			node: [175],
			__typename: [7],
		},
		SampledRecordMediasOrderBy: {},
		SampledRecordMediaCondition: {
			id: [12],
			idRecord: [12],
			ghostUrl: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledRecordMediaFilter: {
			id: [26],
			idRecord: [26],
			ghostUrl: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [179],
			or: [179],
			not: [179],
			__typename: [7],
		},
		SampledUpvotesConnection: {
			nodes: [181],
			edges: [182],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledUpvote: {
			id: [12],
			idUser: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledUpvotesEdge: {
			cursor: [9],
			node: [181],
			__typename: [7],
		},
		SampledUpvotesOrderBy: {},
		SampledUpvoteCondition: {
			id: [12],
			idUser: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledUpvoteFilter: {
			id: [26],
			idUser: [26],
			idLevel: [26],
			dateCreated: [17],
			dateUpdated: [17],
			and: [185],
			or: [185],
			not: [185],
			__typename: [7],
		},
		SampledUsersConnection: {
			nodes: [187],
			edges: [188],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledUser: {
			id: [12],
			steamName: [7],
			banned: [11],
			dateCreated: [6],
			dateUpdated: [6],
			steamId: [22],
			discordId: [22],
			__typename: [7],
		},
		SampledUsersEdge: {
			cursor: [9],
			node: [187],
			__typename: [7],
		},
		SampledUsersOrderBy: {},
		SampledUserCondition: {
			id: [12],
			steamName: [7],
			banned: [11],
			dateCreated: [6],
			dateUpdated: [6],
			steamId: [22],
			discordId: [22],
			__typename: [7],
		},
		SampledUserFilter: {
			id: [26],
			steamName: [18],
			banned: [28],
			dateCreated: [17],
			dateUpdated: [17],
			steamId: [29],
			discordId: [29],
			and: [191],
			or: [191],
			not: [191],
			__typename: [7],
		},
		SampledUserPointsConnection: {
			nodes: [193],
			edges: [194],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledUserPoint: {
			id: [12],
			idUser: [12],
			points: [12],
			dateCreated: [6],
			dateUpdated: [6],
			rank: [12],
			worldRecords: [12],
			__typename: [7],
		},
		SampledUserPointsEdge: {
			cursor: [9],
			node: [193],
			__typename: [7],
		},
		SampledUserPointsOrderBy: {},
		SampledUserPointCondition: {
			id: [12],
			idUser: [12],
			points: [12],
			dateCreated: [6],
			dateUpdated: [6],
			rank: [12],
			worldRecords: [12],
			__typename: [7],
		},
		SampledUserPointFilter: {
			id: [26],
			idUser: [26],
			points: [26],
			dateCreated: [17],
			dateUpdated: [17],
			rank: [26],
			worldRecords: [26],
			and: [197],
			or: [197],
			not: [197],
			__typename: [7],
		},
		SampledVersionsConnection: {
			nodes: [199],
			edges: [200],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledVersion: {
			id: [12],
			minimum: [7],
			latest: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledVersionsEdge: {
			cursor: [9],
			node: [199],
			__typename: [7],
		},
		SampledVersionsOrderBy: {},
		SampledVersionCondition: {
			id: [12],
			minimum: [7],
			latest: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledVersionFilter: {
			id: [26],
			minimum: [18],
			latest: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [203],
			or: [203],
			not: [203],
			__typename: [7],
		},
		SampledWorldRecordGlobalsConnection: {
			nodes: [205],
			edges: [206],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		SampledWorldRecordGlobal: {
			id: [12],
			idRecord: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledWorldRecordGlobalsEdge: {
			cursor: [9],
			node: [205],
			__typename: [7],
		},
		SampledWorldRecordGlobalsOrderBy: {},
		SampledWorldRecordGlobalCondition: {
			id: [12],
			idRecord: [12],
			idLevel: [12],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		SampledWorldRecordGlobalFilter: {
			id: [26],
			idRecord: [26],
			idLevel: [26],
			dateCreated: [17],
			dateUpdated: [17],
			and: [209],
			or: [209],
			not: [209],
			__typename: [7],
		},
		UsersConnection: {
			nodes: [21],
			edges: [211],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		UsersEdge: {
			cursor: [9],
			node: [21],
			__typename: [7],
		},
		UsersOrderBy: {},
		UserCondition: {
			id: [12],
			steamName: [7],
			banned: [11],
			dateCreated: [6],
			dateUpdated: [6],
			steamId: [22],
			discordId: [22],
			__typename: [7],
		},
		VersionsConnection: {
			nodes: [215],
			edges: [216],
			pageInfo: [10],
			totalCount: [12],
			__typename: [7],
		},
		Version: {
			nodeId: [2],
			id: [12],
			minimum: [7],
			latest: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		VersionsEdge: {
			cursor: [9],
			node: [215],
			__typename: [7],
		},
		VersionsOrderBy: {},
		VersionCondition: {
			id: [12],
			minimum: [7],
			latest: [7],
			dateCreated: [6],
			dateUpdated: [6],
			__typename: [7],
		},
		VersionFilter: {
			id: [26],
			minimum: [18],
			latest: [18],
			dateCreated: [17],
			dateUpdated: [17],
			and: [219],
			or: [219],
			not: [219],
			__typename: [7],
		},
		ZRtmConnection: {
			nodes: [221],
			edges: [222],
			totalCount: [12],
			__typename: [7],
		},
		ZRtmRecord: {
			id: [12],
			idLevel: [12],
			workshopId: [22],
			authorId: [22],
			name: [7],
			imageUrl: [7],
			fileAuthor: [7],
			fileUid: [7],
			validationTimeAuthor: [35],
			validationTimeGold: [35],
			validationTimeSilver: [35],
			validationTimeBronze: [35],
			deleted: [11],
			createdAt: [6],
			updatedAt: [6],
			dateCreated: [6],
			dateUpdated: [6],
			amountCheckpoints: [12],
			amountFinishes: [12],
			amountBlocks: [12],
			numRecords: [5],
			__typename: [7],
		},
		ZRtmEdge: {
			cursor: [9],
			node: [221],
			__typename: [7],
		},
		ZRtmRecordFilter: {
			id: [26],
			idLevel: [26],
			workshopId: [29],
			authorId: [29],
			name: [18],
			imageUrl: [18],
			fileAuthor: [18],
			fileUid: [18],
			validationTimeAuthor: [34],
			validationTimeGold: [34],
			validationTimeSilver: [34],
			validationTimeBronze: [34],
			deleted: [28],
			createdAt: [17],
			updatedAt: [17],
			dateCreated: [17],
			dateUpdated: [17],
			amountCheckpoints: [26],
			amountFinishes: [26],
			amountBlocks: [26],
			numRecords: [16],
			and: [223],
			or: [223],
			not: [223],
			__typename: [7],
		},
		Mutation: {
			updateWorldRecordGlobal: [
				225,
				{
					input: [226, 'UpdateWorldRecordGlobalInput!'],
				},
			],
			__typename: [7],
		},
		UpdateWorldRecordGlobalPayload: {
			clientMutationId: [7],
			query: [0],
			__typename: [7],
		},
		UpdateWorldRecordGlobalInput: {
			clientMutationId: [7],
			__typename: [7],
		},
	},
};
